<?php
/** Simple administration of restored services. Every read/write stays in the active PBX. */
class pbx_admin {
    private PDO $db;
    private string $domain;
    public function __construct(?PDO $db=null){$this->db=$db??database::new()->db;$this->domain=$_SESSION['domain_uuid'];if(!(new pbx_setup($this->db))->canManage()||!(new pbx_tenants($this->db))->canDomain($this->domain))throw new RuntimeException('Administrator access required.');}
    private function query(string $sql,array $params=[]): PDOStatement {$s=$this->db->prepare($sql);foreach($params as $k=>$v)$s->bindValue(':'.$k,$v,$v===null?PDO::PARAM_NULL:(is_bool($v)?PDO::PARAM_BOOL:(is_int($v)?PDO::PARAM_INT:PDO::PARAM_STR)));$s->execute();return $s;}
    private function insert(string $table,array $row): void {$keys=array_keys($row);$this->query('insert into '.$table.'('.implode(',',$keys).') values('.implode(',',array_map(fn($k)=>':'.$k,$keys)).')',$row);}
    private function text(array $input,string $key,int $max=120,string $default=''): string {$v=$input[$key]??$default;if(!is_string($v)||mb_strlen($v)>$max||preg_match('/[\x00-\x1f\x7f]/',$v))throw new InvalidArgumentException('Enter a valid '.str_replace('_',' ',$key).'.');return trim($v);}
    private function number(array $in,string $key): string {$v=$this->text($in,$key,32);if(!preg_match('/^\+?[0-9]{1,32}$/D',$v))throw new InvalidArgumentException('Enter a valid number.');return $v;}
    private function integer(array $in,string $key,int $min=1,int $max=86400,int $default=20): int {$v=$in[$key]??$default;if(is_array($v)||is_bool($v)||filter_var($v,FILTER_VALIDATE_INT,['options'=>['min_range'=>$min,'max_range'=>$max]])===false)throw new InvalidArgumentException('Enter a valid '.str_replace('_',' ',$key).'.');return (int)$v;}
    public function restored(): bool {return (bool)$this->query('select 1 from v_pbx_restore where domain_uuid=:d',['d'=>$this->domain])->fetchColumn();}
    public function config(bool $lock=false): array {$r=$this->query('select config from v_pbx_restore where domain_uuid=:d'.($lock?' for update':''),['d'=>$this->domain])->fetchColumn();if(!$r)throw new RuntimeException('Choose a restored PBX first.');return json_decode($r,true,512,JSON_THROW_ON_ERROR);}
    public function report(): array {$r=$this->query('select report from v_pbx_restore where domain_uuid=:d',['d'=>$this->domain])->fetchColumn();return $r?json_decode($r,true,512,JSON_THROW_ON_ERROR):[];}
    public function initialize(string $realm,string $timezone='UTC'): void {
        if(!$this->db->inTransaction())throw new LogicException('Initialization requires a transaction.');
        if($this->query('select domain_name from v_domains where domain_uuid=:d for update',['d'=>$this->domain])->fetchColumn()!==$realm)throw new InvalidArgumentException('Choose the active PBX address.');
        if($this->restored())throw new InvalidArgumentException('This PBX is already configured.');
        if(!preg_match('/^[a-z0-9.-]+$/D',$realm)||!in_array($timezone,DateTimeZone::listIdentifiers(),true))throw new InvalidArgumentException('Choose a valid PBX address and timezone.');
        if($this->query('select 1 from v_extensions where domain_uuid=:d limit 1',['d'=>$this->domain])->fetchColumn())throw new InvalidArgumentException('This PBX already has users.');
        $media=pbx_paths::media().'/'.$this->domain;if(!is_dir($media)&&!mkdir($media,0700,true))throw new RuntimeException('Private media storage is unavailable.');
        $config=['realm'=>$realm,'timezone'=>$timezone,'origin'=>'OpenWeb PBX','users'=>new stdClass,'trunks'=>new stdClass];
        foreach(['queues','ring_groups','receptionists','departments','inbound_rules','outbound_rules','phones','contacts','specials','scripts'] as $key)$config[$key]=[];
        $this->query("insert into v_pbx_restore(domain_uuid,source_version,config,report) values(:d,'OpenWeb PBX 1.0.2',cast(:c as jsonb),'{}')",['d'=>$this->domain,'c'=>json_encode($config,JSON_THROW_ON_ERROR)]);
        $this->newDialplan('','outbound',$config,'all');
        $this->newDialplan('*97','voicemail_login',$config,'all');
    }
    public function services(): array {return $this->query('select s.domain_uuid,s.service_name,t.tenant_name from v_pbx_services s join v_pbx_tenants t on t.tenant_uuid=s.tenant_uuid join v_domains sd on sd.domain_uuid=s.domain_uuid where t.owner_user_uuid=:u and t.enabled and sd.domain_enabled order by s.created_at',['u'=>$_SESSION['user_uuid']])->fetchAll(PDO::FETCH_ASSOC);}
    public static function openPreferred(): void {
        $setup=new pbx_setup;if(!$setup->canManage())return;$db=database::new()->db;
        $s=$db->prepare('select domain_name from v_domains where domain_uuid=:d');$s->execute(['d'=>$_SESSION['domain_uuid']]);if($s->fetchColumn()!==pbx_paths::host())return;
        $s=$db->prepare('select s.domain_uuid from v_pbx_services s join v_pbx_tenants t on t.tenant_uuid=s.tenant_uuid join v_pbx_restore r on r.domain_uuid=s.domain_uuid join v_domains sd on sd.domain_uuid=s.domain_uuid where t.owner_user_uuid=:u and t.enabled and sd.domain_enabled order by r.restored_at desc limit 1');$s->execute(['u'=>$_SESSION['user_uuid']]);$d=$s->fetchColumn();if($d)$setup->switchDomain($d);
    }
    private function saveConfig(array $config): void {$this->query('update v_pbx_restore set config=cast(:c as jsonb) where domain_uuid=:d',['c'=>json_encode($config,JSON_THROW_ON_ERROR),'d'=>$this->domain]);}
    private function changed(?string $trunk=null,?string $queue=null): void {
        settings::clear_cache();$cache=new cache;$realm=$_SESSION['domain_name'];$cache->delete('dialplan:'.$realm);$cache->delete('dialplan:ingress@'.$realm);$cache->delete(gethostname().':configuration:sofia.conf');$cache->delete(gethostname().':configuration:callcenter.conf');$cache->delete('configuration:callcenter.conf');
        foreach($this->config()['users'] as $number=>$u){$cache->delete('directory:'.$u['auth_id'].'@'.$realm);$cache->delete('directory:'.$number.'@'.$realm);}
        try{event_socket::api('reloadxml');if($trunk&&is_uuid($trunk)){event_socket::api('sofia profile external killgw '.$trunk);event_socket::api('sofia profile external rescan');}if($queue&&preg_match('/^[0-9]{2,10}$/D',$queue))event_socket::api('callcenter_config queue unload '.$queue.'@'.$realm);}catch(Throwable){error_log('OpenWeb PBX: call settings saved; reload unavailable');}
    }
    private function row(array $rows,string $key,string $field='number'): array {foreach($rows as $i=>$r)if((string)$r[$field]===$key)return [$i,$r];throw new InvalidArgumentException('This item is not in your PBX.');}
    public function destinations(array $config): array {
        $out=['None:'=>'End Call'];foreach($config['users'] as $n=>$u){$out['Extension:'.$n]=$n.' · '.$u['name'];if($u['voicemail_enabled'])$out['VoiceMail:'.$n]=$n.' · '.$u['name'].' · Voicemail';}
        foreach(['queues'=>'Queue','ring_groups'=>'RingGroup','receptionists'=>'IVR','scripts'=>'RoutePoint'] as $key=>$kind)foreach($config[$key] as $r)$out[$kind.':'.$r['number']]=$r['number'].' · '.$r['name'];$out['External:']='External Number';return $out;
    }
    private function destination(array $in,string $key,array $config,array $fallback=['type'=>'None','number'=>'','external'=>'']): array {
        if(!isset($in[$key]))return $fallback;$value=$this->text($in,$key,50);$choices=$this->destinations($config);if(!isset($choices[$value]))throw new InvalidArgumentException('Choose a call destination.');[$type,$number]=explode(':',$value,2);$external='';if($type==='External')$external=$this->number($in,$key.'_external');return ['type'=>$type,'number'=>$number,'external'=>$external];
    }
    private function selectedUsers(array $in,string $key,array $config): array {$rows=$in[$key]??[];if(!is_array($rows)||count($rows)>1000)throw new InvalidArgumentException('Choose users from this PBX.');$out=[];foreach($rows as $n){if(!is_string($n)||!isset($config['users'][$n]))throw new InvalidArgumentException('Choose users from this PBX.');$out[$n]=['number'=>$n,'status'=>'LoggedIn','skill'=>'0'];}return array_values($out);}
    public function save(string $type,string $key,array $in): string {
        $this->db->beginTransaction();try{$c=$this->config(true);$result=match($type){'user'=>$this->saveUser($key,$in,$c),'trunk'=>$this->saveTrunk($key,$in,$c),'department'=>$this->saveDepartment($key,$in,$c),'hours'=>$this->saveHours($key,$in,$c),'queue','ring_group','receptionist'=>$this->saveHandling($type,$key,$in,$c),'outbound'=>$this->saveOutbound($key,$in,$c),'incoming'=>$this->saveIncoming($key,$in,$c),'script'=>$this->saveScript($key,$in,$c),default=>throw new InvalidArgumentException('Choose an admin page.')};$this->saveConfig($c);$this->db->commit();}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}$this->changed($type==='trunk'?$this->config()['trunks'][$result]['gateway_uuid']:null,$type==='queue'?$result:null);return $result;
    }
    private function newDialplan(string $number,string $mode,array $c,string $dispatch=''): string {
        $id=uuid();$d=new DOMDocument('1.0','UTF-8');$x=$d->appendChild($d->createElement('extension'));$x->setAttribute('name','OpenWeb '.$mode.' '.$number);$x->setAttribute('uuid',$id);$x->setAttribute('continue','false');$condition=$x->appendChild($d->createElement('condition'));$condition->setAttribute('field','destination_number');$condition->setAttribute('expression',$number===''?'^.+$':'^'.preg_quote($number,'~').'$');
        foreach([['set','domain_uuid='.$this->domain],['set','domain_name='.$c['realm']],['lua','app.lua pbx_setup '.$mode.' '.($dispatch?:$number)]] as [$a,$v]){$n=$condition->appendChild($d->createElement('action'));$n->setAttribute('application',$a);$n->setAttribute('data',$v);}
        $this->insert('v_dialplans',['dialplan_uuid'=>$id,'domain_uuid'=>$this->domain,'dialplan_name'=>'OpenWeb '.$mode.' '.$number,'dialplan_number'=>$number,'dialplan_context'=>($mode==='incoming'?'ingress@':'').$c['realm'],'dialplan_order'=>$mode==='outbound'?900:80,'dialplan_continue'=>false,'dialplan_enabled'=>$mode!=='incoming','dialplan_xml'=>$d->saveXML($x),'dialplan_description'=>'Manage in Admin']);return $id;
    }
    private function availableNumber(string $number,array $c): void {if(!preg_match('/^[0-9]{2,10}$/D',$number))throw new InvalidArgumentException('Use an extension with 2 to 10 digits.');if(isset($c['users'][$number]))throw new InvalidArgumentException('That extension is already used.');foreach(['queues','ring_groups','receptionists','scripts','specials'] as $kind)foreach($c[$kind] as $r)if($r['number']===$number)throw new InvalidArgumentException('That extension is already used.');}
    private function saveUser(string $key,array $in,array &$c): string {
        $new=$key==='new';if($new){$key=$this->number($in,'number');$this->availableNumber($key,$c);$id=uuid();$auth='ow-'.$key;$password=bin2hex(random_bytes(18));$pin=(string)random_int(100000,999999);$this->insert('v_extensions',['extension_uuid'=>$id,'domain_uuid'=>$this->domain,'extension'=>$auth,'password'=>$password,'effective_caller_id_number'=>$key,'accountcode'=>$c['realm'],'user_context'=>$c['realm'],'dial_domain'=>$c['realm'],'enabled'=>true,'call_timeout'=>20,'max_registrations'=>5,'extension_type'=>'default']);$vm=uuid();$this->insert('v_voicemails',['voicemail_uuid'=>$vm,'domain_uuid'=>$this->domain,'voicemail_id'=>$key,'voicemail_password'=>$pin,'voicemail_enabled'=>true,'voicemail_tutorial'=>true]);$vmDest=['type'=>'VoiceMail','number'=>$key,'external'=>''];$profiles=[];foreach(['Available','Away','Out of office','Custom 1','Custom 2'] as $status)$profiles[$status]=['name'=>$status,'timeout'=>20,'disable_ring_groups'=>!in_array($status,['Available','Custom 1'],true),'ring_mobile'=>false,'queue_status'=>'-1','busy_detection'=>'UsePBXStatus','available'=>in_array($status,['Available','Custom 1'],true)?array_fill_keys(['NoAnswer','Busy','NotRegistered'],['internal_inactive'=>true,'all'=>$vmDest,'internal'=>$vmDest]):[],'away'=>in_array($status,['Available','Custom 1'],true)?[]:array_fill_keys(['Internal','External'],['outside_inactive'=>true,'all'=>$vmDest,'outside'=>$vmDest])];$c['users'][$key]=['number'=>$key,'auth_id'=>$auth,'extension_uuid'=>$id,'voicemail_uuid'=>$vm,'dialplan_uuid'=>$this->newDialplan($key,'user',$c),'profiles'=>$profiles,'profile'=>'Available','queue_status'=>'LoggedIn','auto_status'=>'0','record_external_only'=>false,'hours'=>['hours'=>['type'=>'OfficeHours','periods'=>[]],'breaks'=>['periods'=>[]],'outside'=>'','break'=>'','holiday'=>'']];}
        if(!isset($c['users'][$key]))throw new InvalidArgumentException('This user is not in your PBX.');$u=&$c['users'][$key];$name=$this->text($in,'name',80);if($name===''||preg_match('/["<>&]/',$name))throw new InvalidArgumentException('Enter the user name.');$email=$this->text($in,'email',254);if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))throw new InvalidArgumentException('Enter a valid email address.');$status=$this->text($in,'profile',40,'Available');if(!isset($u['profiles'][$status]))throw new InvalidArgumentException('Choose a user status.');
        $u['name']=$name;$u['email']=$email;$u['profile']=$status;$u['enabled']=!empty($in['enabled']);$u['voicemail_enabled']=!empty($in['voicemail_enabled']);$u['record_calls']=!empty($in['record_calls']);$u['mobile']=$this->text($in,'mobile',32);if($u['mobile']!==''&&!preg_match('/^\+?[0-9]{1,32}$/D',$u['mobile']))throw new InvalidArgumentException('Enter a mobile number.');$u['outbound_caller_id']=$this->text($in,'outbound_caller_id',32);if($u['outbound_caller_id']!==''&&!preg_match('/^\+?[0-9]{1,32}$/D',$u['outbound_caller_id']))throw new InvalidArgumentException('Enter a caller ID number.');$oldFlags=(int)($u['auto_status']??0);$u['auto_status']=(string)(!empty($in['auto_status'])?($oldFlags|1):($oldFlags&~1));$p=&$u['profiles'][$status];$editProfile=$this->text($in,'editing_profile',40,$status);if($editProfile===$status){$p['timeout']=$this->integer($in,'timeout',1,600);$p['ring_mobile']=!empty($in['ring_mobile']);
        foreach(['NoAnswer'=>'no_answer','Busy'=>'busy','NotRegistered'=>'not_registered'] as $reason=>$field){if(isset($p['available'][$reason]))$p['available'][$reason]['all']=$this->destination($in,$field,$c,$p['available'][$reason]['all']);}
        if(!empty($p['away']))foreach(['Internal','External'] as $origin)$p['away'][$origin]['all']=$this->destination($in,'away',$c,$p['away'][$origin]['all']);}
        $parts=explode(' ',$name,2);$this->query('update v_extensions set effective_caller_id_name=:n,directory_first_name=:first,directory_last_name=:last,enabled=:on,call_timeout=:time,outbound_caller_id_number=:cid where domain_uuid=:d and extension_uuid=:id',['n'=>$name,'first'=>$parts[0],'last'=>$parts[1]??'','on'=>$u['enabled'],'time'=>$p['timeout'],'cid'=>$u['outbound_caller_id'],'d'=>$this->domain,'id'=>$u['extension_uuid']]);
        $option=$this->text($in,'voicemail_email',30,$u['voicemail_email']??'None');if(!in_array($option,['None','Notification','Attachment','AttachmentAndDelete'],true))throw new InvalidArgumentException('Choose a voicemail email option.');$u['voicemail_email']=$option;
        if(isset($in['greeting_id'])){$greeting=$this->text($in,'greeting_id',10);if($greeting!==''&&!in_array($greeting,array_column($u['greetings']??[],'id'),true))throw new InvalidArgumentException('Choose a greeting for this user.');$u['greeting_id']=$greeting;$this->query('update v_voicemails set greeting_id=:g where domain_uuid=:d and voicemail_uuid=:id',['g'=>$greeting===''?null:$greeting,'d'=>$this->domain,'id'=>$u['voicemail_uuid']]);}
        $this->query('update v_voicemails set voicemail_mail_to=:mail,voicemail_enabled=:on,voicemail_description=:name,voicemail_file=:file,voicemail_local_after_email=:keep where domain_uuid=:d and voicemail_uuid=:id',['mail'=>$option==='None'?'':$email,'on'=>$u['voicemail_enabled'],'name'=>$name,'file'=>in_array($option,['Attachment','AttachmentAndDelete'],true)?'attach':'link','keep'=>$option!=='AttachmentAndDelete','d'=>$this->domain,'id'=>$u['voicemail_uuid']]);
        $department=$this->text($in,'department',40);foreach($c['departments'] as &$dep){$dep['members']=array_values(array_filter($dep['members'],fn($m)=>!($m['number']===$key&&$m['primary'])));if($dep['number']===$department){$found=false;foreach($dep['members'] as &$m)if($m['number']===$key){$m['primary']=true;$found=true;}unset($m);if(!$found)$dep['members'][]=['number'=>$key,'primary'=>true];}}unset($dep);return $key;
    }
    private function saveTrunk(string $key,array $in,array &$c): string {
        if($key==='new'){$key='ow-'.substr(str_replace('-','',uuid()),0,12);$id=uuid();$c['trunks'][$key]=['number'=>$key,'gateway_uuid'=>$id,'name'=>'','host'=>'','port'=>5060,'transport'=>'udp','register'=>false,'enabled'=>false,'allowed_ips'=>[],'main_number'=>'','caller_id'=>'','limit'=>10,'expires'=>180,'type'=>'Provider','headers'=>[]];$this->insert('v_gateways',['gateway_uuid'=>$id,'domain_uuid'=>$this->domain,'gateway'=>'New SIP Trunk','context'=>'ingress@'.$c['realm'],'profile'=>'external','enabled'=>false,'register'=>false,'register_transport'=>'udp','expire_seconds'=>180,'retry_seconds'=>30]);}
        if(!isset($c['trunks'][$key]))throw new InvalidArgumentException('This trunk is not in your PBX.');$t=&$c['trunks'][$key];$name=$this->text($in,'name',80);$host=strtolower($this->text($in,'host',253));if($name===''||(!filter_var($host,FILTER_VALIDATE_IP)&&!preg_match('/^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)*[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/D',$host)))throw new InvalidArgumentException('Enter the trunk name and provider server.');$port=$this->integer($in,'port',1,65535,5060);$auth=$this->text($in,'authentication',12,'ip');if(!in_array($auth,['ip','password'],true))throw new InvalidArgumentException('Choose an authentication method.');$user=$this->text($in,'username',128);if(!preg_match('/^[A-Za-z0-9_.+@-]{0,128}$/D',$user))throw new InvalidArgumentException('Enter a valid username.');$password=$in['password']??'';if(!is_string($password)||strlen($password)>256||preg_match('/[\x00-\x1f]/',$password)||str_contains($password,'${'))throw new InvalidArgumentException('Enter a valid password.');
        $ips=preg_split('/[ ,\r\n]+/',$this->text($in,'allowed_ips',1000),-1,PREG_SPLIT_NO_EMPTY);foreach($ips as $ip)if(!filter_var($ip,FILTER_VALIDATE_IP))throw new InvalidArgumentException('Enter the IP addresses supplied by your provider.');if($auth==='password'&&$user==='')throw new InvalidArgumentException('Enter the provider username.');$enabled=!empty($in['enabled']);if($enabled&&!$ips)throw new InvalidArgumentException('Add the provider IP addresses before connecting the trunk.');if($enabled&&$t['type']==='BridgeMaster')throw new InvalidArgumentException('This 3CX bridge needs a new connection.');
        $t['name']=$name;$t['host']=$host;$t['port']=$port;$t['register']=$auth==='password';$t['enabled']=$enabled;$t['allowed_ips']=array_values(array_unique($ips));$t['main_number']=$this->text($in,'main_number',32);$t['caller_id']=$this->text($in,'caller_id',32);foreach(['main_number','caller_id'] as $field)if($t[$field]!==''&&!preg_match('/^\+?[0-9]{1,32}$/D',$t[$field]))throw new InvalidArgumentException('Enter a valid phone number.');
        $params=['name'=>$name,'proxy'=>$host.':'.$port,'user'=>$auth==='ip'?'':$user,'register'=>$t['register'],'on'=>$enabled,'d'=>$this->domain,'id'=>$t['gateway_uuid']];$sql='update v_gateways set gateway=:name,proxy=:proxy,username=:user,auth_username=:user,register=:register,enabled=:on';if($auth==='ip'||$password!==''){$sql.=',password=:password';$params['password']=$auth==='ip'?'':$password;}$this->query($sql.' where domain_uuid=:d and gateway_uuid=:id',$params);
        // Refresh existing number checks when the provider changes its sending addresses.
        foreach($c['inbound_rules'] as $rule)if($rule['trunk_id']===$key&&!empty($rule['enabled']))$this->saveIncoming($rule['rule_id'],['enabled'=>$enabled?'1':'','use_outside'=>$rule['use_outside']?'1':''],$c);
        return $key;
    }
    private function saveDepartment(string $key,array $in,array &$c): string {
        $new=$key==='new';if($new){$key='GRP'.substr(str_replace('-','',uuid()),0,12);$i=count($c['departments']);$c['departments'][]=['number'=>$key,'name'=>'','members'=>[],'timezone'=>$c['timezone'],'hours'=>['type'=>'AllHours','periods'=>[]],'breaks'=>['type'=>'SpecificHours','periods'=>[]],'holidays'=>[]];}else [$i]=$this->row($c['departments'],$key);
        $name=$this->text($in,'name');if($name==='')throw new InvalidArgumentException('Enter a department name.');$c['departments'][$i]['name']=$name;$members=$this->selectedUsers($in,'members',$c);$other=array_values(array_filter($c['departments'][$i]['members'],fn($m)=>!isset($c['users'][$m['number']])));$c['departments'][$i]['members']=array_merge($other,array_map(fn($m)=>['number'=>$m['number'],'primary'=>true],$members));foreach($c['departments'] as $j=>&$d)if($j!==$i)foreach($d['members'] as &$m)foreach($members as $selected)if($selected['number']===$m['number'])$m['primary']=false;unset($m,$d);return $key;
    }
    private function saveHours(string $key,array $in,array &$c): string {
        [$i,$d]=$this->row($c['departments'],$key);$zone=$this->text($in,'timezone',80);if(!in_array($zone,DateTimeZone::listIdentifiers(),true))throw new InvalidArgumentException('Choose a timezone.');$periods=[];
        if(!empty($in['always_open']))$hours=['type'=>'AllHours','periods'=>[]];else{$days=$in['days']??[];if(!is_array($days))throw new InvalidArgumentException('Choose office hours.');foreach($days as $day=>$row){if(!ctype_digit((string)$day)||(int)$day>6||!is_array($row))throw new InvalidArgumentException('Choose office hours.');if(empty($row['open']))continue;foreach(['start','end'] as $f){$time=$this->text($row,$f,5);if(!preg_match('/^(?:[01][0-9]|2[0-3]):[0-5][0-9]$/D',$time)&&!($f==='end'&&$time==='24:00'))throw new InvalidArgumentException('Enter a valid opening and closing time.');$row[$f]=$time;}if($row['start']>=$row['end'])throw new InvalidArgumentException('Closing time must be after opening time.');$periods[]=['day'=>(int)$day,'start'=>$row['start'],'end'=>$row['end']];}$hours=['type'=>'SpecificHoursExcludingHolidays','periods'=>$periods,'ignore_holidays'=>false];}
        $c['departments'][$i]['timezone']=$zone;$c['departments'][$i]['hours']=$hours;return $key;
    }
    private function saveHandling(string $type,string $key,array $in,array &$c): string {
        $kind=['queue'=>'queues','ring_group'=>'ring_groups','receptionist'=>'receptionists'][$type];$mode=['queue'=>'queue','ring_group'=>'group','receptionist'=>'ivr'][$type];$new=$key==='new';
        if($new){$key=$this->number($in,'number');$this->availableNumber($key,$c);$i=count($c[$kind]);$c[$kind][]=['number'=>$key,'name'=>'','uuid'=>uuid(),'dialplan_uuid'=>$this->newDialplan($key,$mode,$c),'hours'=>['hours'=>['type'=>'AllHours','periods'=>[]],'breaks'=>['periods'=>[]],'outside'=>'','break'=>'','holiday'=>'']];}else [$i]=$this->row($c[$kind],$key);
        $r=&$c[$kind][$i];$name=$this->text($in,'name');if($name==='')throw new InvalidArgumentException('Enter a name.');$r['name']=$name;$r['timeout']=$this->integer($in,'timeout',1,86400,30);
        if($type!=='receptionist'){$members=$this->selectedUsers($in,'members',$c);if(!$members)throw new InvalidArgumentException('Choose at least one user.');$oldMembers=$r['members']??[];foreach($members as &$m)foreach($oldMembers as $old)if($old['number']===$m['number'])$m=array_merge($old,$m);unset($m);$r['members']=$members;$r['destination']=$this->destination($in,'destination',$c,$r['destination']??['type'=>'None','number'=>'','external'=>'']);}
        if($type==='ring_group'){$r['strategy']='RingAll';if($new)$this->insert('v_ring_groups',['ring_group_uuid'=>$r['uuid'],'domain_uuid'=>$this->domain,'dialplan_uuid'=>$r['dialplan_uuid'],'ring_group_extension'=>$key,'ring_group_context'=>$c['realm'],'ring_group_enabled'=>true]);$this->query('update v_ring_groups set ring_group_name=:n,ring_group_call_timeout=:t,ring_group_strategy=\'simultaneous\',ring_group_timeout_app=\'lua\',ring_group_timeout_data=:data where domain_uuid=:d and ring_group_uuid=:id',['n'=>$name,'t'=>$r['timeout'],'data'=>'app.lua pbx_setup group_timeout '.$key,'d'=>$this->domain,'id'=>$r['uuid']]);$this->query('delete from v_ring_group_destinations where domain_uuid=:d and ring_group_uuid=:id',['d'=>$this->domain,'id'=>$r['uuid']]);foreach($members as $m)$this->insert('v_ring_group_destinations',['ring_group_destination_uuid'=>uuid(),'domain_uuid'=>$this->domain,'ring_group_uuid'=>$r['uuid'],'destination_number'=>$m['number'],'destination_timeout'=>$r['timeout'],'destination_enabled'=>true]);}
        elseif($type==='queue'){$r['strategy']='PollingStrategyRingAll';$r['ring_timeout']=$this->integer($in,'ring_timeout',1,600,30);$r['wrap_up']=$this->integer($in,'wrap_up',0,600,2);$r['intro']=$this->audio($in,'intro',$r['intro']??'');$r['moh']=$this->audio($in,'moh',$r['moh']??'');$r['announce_position']=$r['announce_position']??false;$r['announce_interval']=$r['announce_interval']??30;$r['callback']=$r['callback']??'-1';
            if(isset($in['callback_mode'])){$mode=$this->text($in,'callback_mode',16);if(!in_array($mode,['disabled','request','offer','automatic'],true))throw new InvalidArgumentException('Choose a callback option.');$r['callback_mode']=$mode;$r['callback_after']=$this->integer($in,'callback_after',1,86400,600);if(in_array($mode,['offer','automatic'],true)&&$r['callback_after']>$r['timeout'])throw new InvalidArgumentException('Offer callbacks before the maximum queue wait ends.');$r['callback_attempts']=$this->integer($in,'callback_attempts',1,5,3);$prefix=$this->text($in,'callback_prefix',10);if(!preg_match('/^[0-9]{0,10}$/D',$prefix))throw new InvalidArgumentException('Enter a valid callback prefix.');$r['callback_prefix']=$prefix;$r['callback']=$mode==='disabled'?'-1':($mode==='request'?'0':(string)$r['callback_after']);}
            $queueWait=in_array($r['callback_mode']??'disabled',['offer','automatic'],true)?min($r['timeout'],$r['callback_after']):$r['timeout'];
            if($new)$this->insert('v_call_center_queues',['call_center_queue_uuid'=>$r['uuid'],'domain_uuid'=>$this->domain,'dialplan_uuid'=>$r['dialplan_uuid'],'queue_extension'=>$key,'queue_context'=>$c['realm'],'queue_time_base_score'=>'system']);$this->query('update v_call_center_queues set queue_name=:n,queue_strategy=\'ring-all\',queue_max_wait_time=:t,queue_max_wait_time_with_no_agent=:t,queue_moh_sound=:moh,queue_greeting=:intro,queue_announce_position=:announce where domain_uuid=:d and call_center_queue_uuid=:id',['n'=>$name,'t'=>$queueWait,'moh'=>$r['moh']?:'local_stream://default','intro'=>$r['intro'],'announce'=>$r['announce_position'],'d'=>$this->domain,'id'=>$r['uuid']]);$this->query('delete from v_call_center_tiers where domain_uuid=:d and call_center_queue_uuid=:id',['d'=>$this->domain,'id'=>$r['uuid']]);
            foreach($r['members'] as $pos=>&$m){$u=$c['users'][$m['number']];$a=$m['agent_uuid']??uuid();if(empty($m['agent_uuid']))$this->insert('v_call_center_agents',['call_center_agent_uuid'=>$a,'domain_uuid'=>$this->domain,'agent_name'=>$u['name'].' '.$key,'agent_id'=>$m['number'],'agent_type'=>'callback','agent_status'=>'Available']);$m['agent_uuid']=$a;$this->query('update v_call_center_agents set agent_call_timeout=:t,agent_wrap_up_time=:w,agent_contact=:contact where domain_uuid=:d and call_center_agent_uuid=:id',['t'=>$r['ring_timeout'],'w'=>$r['wrap_up'],'contact'=>'[leg_timeout='.$r['ring_timeout'].']user/'.$u['auth_id'].'@'.$c['realm'],'d'=>$this->domain,'id'=>$a]);$this->insert('v_call_center_tiers',['call_center_tier_uuid'=>uuid(),'domain_uuid'=>$this->domain,'call_center_queue_uuid'=>$r['uuid'],'call_center_agent_uuid'=>$a,'queue_name'=>$key.'@'.$c['realm'],'agent_name'=>$a,'tier_level'=>1,'tier_position'=>$pos+1]);}unset($m);
        }else{$r['prompt']=$this->audio($in,'prompt',$r['prompt']??'');$r['timeout_destination']=$this->destination($in,'destination',$c,$r['timeout_destination']??['type'=>'None','number'=>'','external'=>'']);$options=$in['options']??[];if(!is_array($options)||count($options)>12)throw new InvalidArgumentException('Choose receptionist options.');$r['options']=[];foreach($options as $digit=>$row){if(!preg_match('/^[0-9*#]$/D',(string)$digit)||!is_array($row))throw new InvalidArgumentException('Choose a receptionist key.');if(empty($row['destination']))continue;$r['options'][]=['digit'=>(string)$digit,'destination'=>$this->destination($row,'destination',$c)];}
            if($new)$this->insert('v_ivr_menus',['ivr_menu_uuid'=>$r['uuid'],'domain_uuid'=>$this->domain,'dialplan_uuid'=>$r['dialplan_uuid'],'ivr_menu_extension'=>$key,'ivr_menu_context'=>$c['realm'],'ivr_menu_enabled'=>true]);$this->query('update v_ivr_menus set ivr_menu_name=:n,ivr_menu_greet_long=:prompt,ivr_menu_greet_short=:prompt,ivr_menu_timeout=:t where domain_uuid=:d and ivr_menu_uuid=:id',['n'=>$name,'prompt'=>$r['prompt'],'t'=>$r['timeout']*1000,'d'=>$this->domain,'id'=>$r['uuid']]);$this->query('delete from v_ivr_menu_options where domain_uuid=:d and ivr_menu_uuid=:id',['d'=>$this->domain,'id'=>$r['uuid']]);foreach($r['options'] as $j=>$o)$this->insert('v_ivr_menu_options',['ivr_menu_option_uuid'=>uuid(),'domain_uuid'=>$this->domain,'ivr_menu_uuid'=>$r['uuid'],'ivr_menu_option_digits'=>$o['digit'],'ivr_menu_option_action'=>'menu-exec-app','ivr_menu_option_param'=>'lua app.lua pbx_setup ivr_key '.$key.':'.$o['digit'],'ivr_menu_option_order'=>$j+1,'ivr_menu_option_enabled'=>true]);}
        return $key;
    }
    private function audio(array $in,string $field,string $existing): string {if(!isset($in[$field]))return $existing;$id=$this->text($in,$field,36);if($id==='')return '';if(!is_uuid($id))throw new InvalidArgumentException('Choose an audio file.');$path=$this->query("select file_path from v_pbx_media where domain_uuid=:d and media_uuid=:id and category='prompts'",['d'=>$this->domain,'id'=>$id])->fetchColumn();if(!$path)throw new InvalidArgumentException('Choose an audio file from this PBX.');return $path;}
    private function saveOutbound(string $key,array $in,array &$c): string {
        if($key==='new'){$key=uuid();$i=count($c['outbound_rules']);$c['outbound_rules'][]=['rule_id'=>$key,'priority'=>$i,'ranges'=>[],'departments'=>[]];}else [$i]=$this->row($c['outbound_rules'],$key,'rule_id');$r=&$c['outbound_rules'][$i];$r['name']=$this->text($in,'name');$r['prefix']=$this->text($in,'prefix',120);$r['lengths']=$this->text($in,'lengths',120);if($r['name']==='')throw new InvalidArgumentException('Enter a rule name.');foreach(explode(',',$r['prefix']) as $p)if(!preg_match('/^\+?[0-9]{0,20}$/D',trim($p)))throw new InvalidArgumentException('Enter prefixes separated by commas.');if(!preg_match('/^[0-9,\- ]{0,120}$/D',$r['lengths']))throw new InvalidArgumentException('Enter number lengths separated by commas.');$rows=$in['routes']??[];if(!is_array($rows)||count($rows)>5)throw new InvalidArgumentException('Choose up to five routes.');$r['routes']=[];foreach($rows as $route){if(!is_array($route)||empty($route['trunk_id']))continue;$trunk=$this->text($route,'trunk_id',40);if(!isset($c['trunks'][$trunk]))throw new InvalidArgumentException('Choose a trunk from this PBX.');$prepend=$this->text($route,'prepend',20);$callerID=$this->text($route,'caller_id',32);if(!preg_match('/^\+?[0-9]{0,20}$/D',$prepend)||!preg_match('/^\+?[0-9]{0,32}$/D',$callerID))throw new InvalidArgumentException('Enter valid numbers.');$r['routes'][]=['trunk_id'=>$trunk,'strip'=>$this->integer($route,'strip',0,20,0),'prepend'=>$prepend,'caller_id'=>$callerID];}if(!$r['routes'])throw new InvalidArgumentException('Choose at least one route.');return $key;
    }
    private function saveIncoming(string $key,array $in,array &$c): string {
        if($key==='new'){$key=uuid();$trunk=$this->text($in,'trunk_id',40);if(!isset($c['trunks'][$trunk]))throw new InvalidArgumentException('Choose a SIP trunk.');$number=$this->number($in,'number');$i=count($c['inbound_rules']);$empty=['type'=>'None','number'=>'','external'=>''];$dp=$this->newDialplan($number,'incoming',$c,$key);$c['inbound_rules'][]=['rule_id'=>$key,'trunk_id'=>$trunk,'number'=>$number,'name'=>$number,'order'=>$i,'condition'=>'BasedOnDID','hours'=>['type'=>'OfficeHours','periods'=>[]],'office'=>$empty,'outside'=>$empty,'holiday'=>$empty,'use_outside'=>false,'use_holiday'=>false,'enabled'=>false,'dialplan_uuid'=>$dp];$this->insert('v_destinations',['destination_uuid'=>$key,'domain_uuid'=>$this->domain,'dialplan_uuid'=>$dp,'destination_type'=>'inbound','destination_number'=>$number,'destination_context'=>'ingress@'.$c['realm'],'destination_app'=>'lua','destination_data'=>'app.lua pbx_setup incoming '.$key,'destination_enabled'=>false,'destination_type_voice'=>1,'destination_description'=>$number]);}
        [$i]=$this->row($c['inbound_rules'],$key,'rule_id');$r=&$c['inbound_rules'][$i];$r['office']=$this->destination($in,'office',$c,$r['office']);$r['outside']=$this->destination($in,'outside',$c,$r['outside']);$r['use_outside']=!empty($in['use_outside']);$enabled=!empty($in['enabled']);$t=$c['trunks'][$r['trunk_id']];if($enabled&&(!$t['enabled']||!$t['allowed_ips']))throw new InvalidArgumentException('Connect the SIP trunk first.');if($enabled)$this->checkIncomingBinding($r,$t,$c);$r['enabled']=$enabled;
        // Both public and gateway ingress must check the source IP before any routing.
        $s=$this->query('select dialplan_xml from v_dialplans where domain_uuid=:d and dialplan_uuid=:id',['d'=>$this->domain,'id'=>$r['dialplan_uuid']])->fetchColumn();$doc=new DOMDocument();$doc->loadXML($s,LIBXML_NONET);$root=$doc->documentElement;foreach(iterator_to_array($root->childNodes) as $node)if($node instanceof DOMElement&&$node->getAttribute('field')==='${sip_network_ip}')$root->removeChild($node);$condition=$doc->createElement('condition');$condition->setAttribute('field','${sip_network_ip}');$condition->setAttribute('expression','^(?:'.implode('|',array_map(fn($ip)=>preg_quote($ip,'~'),$t['allowed_ips'])).')$');$root->insertBefore($condition,$root->firstChild);$this->query('update v_dialplans set dialplan_xml=:xml,dialplan_enabled=:on where domain_uuid=:d and dialplan_uuid=:id',['xml'=>$doc->saveXML($root),'on'=>$enabled,'d'=>$this->domain,'id'=>$r['dialplan_uuid']]);$this->query('update v_destinations set destination_enabled=:on where domain_uuid=:d and destination_uuid=:id',['on'=>$enabled,'d'=>$this->domain,'id'=>$r['rule_id']]);return $key;
    }
    private function checkIncomingBinding(array $rule,array $trunk,array $own): void {
        // Serialize changes to public number ownership across independent PBXs.
        $this->query("select pg_advisory_xact_lock(hashtext('openweb-incoming-number'))");
        $configs=[$own];foreach($this->query('select config from v_pbx_restore where domain_uuid<>:d',['d'=>$this->domain]) as $row)$configs[]=json_decode($row['config'],true,512,JSON_THROW_ON_ERROR);
        foreach($configs as $index=>$config)foreach($config['inbound_rules'] as $other){
            if(empty($other['enabled'])||($index===0&&$other['rule_id']===$rule['rule_id']))continue;
            $otherTrunk=$config['trunks'][$other['trunk_id']]??[];if(empty($otherTrunk['enabled'])||!array_intersect($trunk['allowed_ips'],$otherTrunk['allowed_ips']??[]))continue;
            $a=ltrim($rule['number'],'+');$b=ltrim($other['number'],'+');
            if($a===$b||$a===''||$b===''||str_contains($a,'*')||str_contains($b,'*'))throw new InvalidArgumentException('This number already has an active route from that provider. Keep one active destination per number.');
        }
    }
    private function saveScript(string $key,array $in,array &$c): string {[$i]=$this->row($c['scripts'],$key);$map=$c['scripts'][$i]['pin_map'];$rows=$in['pin_routes']??[];if(!is_array($rows)||count($rows)>100)throw new InvalidArgumentException('Choose PIN menu users.');$pins=array_keys($map);foreach($rows as $index=>$r){if(!ctype_digit((string)$index)||!isset($pins[(int)$index])||!is_array($r))throw new InvalidArgumentException('Choose PIN menu users.');$n=$this->number($r,'number');if(!isset($c['users'][$n]))throw new InvalidArgumentException('Choose a user from this PBX.');$map[$pins[(int)$index]]=$n;}$c['scripts'][$i]['pin_map']=$map;return $key;}
    public function credentials(string $key): array {$c=$this->config();$u=$c['users'][$key]??null;if(!$u)throw new InvalidArgumentException('This user is not in your PBX.');$r=$this->query('select extension,password from v_extensions where domain_uuid=:d and extension_uuid=:id',['d'=>$this->domain,'id'=>$u['extension_uuid']])->fetch(PDO::FETCH_ASSOC);return ['server'=>pbx_paths::host(),'extension'=>$key,'account'=>$r['extension'],'password'=>$r['password'],'domain'=>$c['realm']];}
    public function media(string $category,int $page=0): array {if(!in_array($category,['recordings','voicemails','prompts'],true))throw new InvalidArgumentException('Choose audio files.');$page=max(0,min($page,10000));return $this->query('select media_uuid,title,owner_number,created_at,duration,file_path from v_pbx_media where domain_uuid=:d and category=:c order by created_at desc nulls last,media_uuid limit 100 offset '.($page*100),['d'=>$this->domain,'c'=>$category])->fetchAll(PDO::FETCH_ASSOC);}
    public function mediaFile(string $id): array {if(!is_uuid($id))throw new InvalidArgumentException('Audio unavailable.');$r=$this->query('select file_path,title from v_pbx_media where domain_uuid=:d and media_uuid=:id',['d'=>$this->domain,'id'=>$id])->fetch(PDO::FETCH_ASSOC);if(!$r||!is_file($r['file_path'])||!pbx_paths::contains(pbx_paths::media().'/'.$this->domain,$r['file_path']))throw new InvalidArgumentException('Audio unavailable.');return $r;}
    public function history(int $page=0): array {$page=max(0,min($page,10000));return $this->query('select owner_number,party_number,party_name,call_type,start_time,end_time,end_status from v_pbx_call_history where domain_uuid=:d order by start_time desc nulls last limit 100 offset '.($page*100),['d'=>$this->domain])->fetchAll(PDO::FETCH_ASSOC);}
    public function uploadAudio(array $upload): string {
        if(($upload['error']??1)!==UPLOAD_ERR_OK||!is_string($upload['tmp_name']??null)||!is_uploaded_file($upload['tmp_name'])||($upload['size']??0)>25*1024*1024)throw new InvalidArgumentException('Choose a WAV file smaller than 25 MB.');
        $f=fopen($upload['tmp_name'],'rb');$head=fread($f,12);fclose($f);if(substr($head,0,4)!=='RIFF'||substr($head,8,4)!=='WAVE')throw new InvalidArgumentException('Choose a WAV audio file.');
        $id=uuid();$root=pbx_paths::media().'/'.$this->domain;if(!is_dir($root)&&!mkdir($root,0700,true))throw new RuntimeException('Audio storage is unavailable.');$path=$root.'/'.$id.'.wav';$title=basename(str_replace('\\','/',(string)($upload['name']??'prompt.wav')));if(mb_strlen($title)>120||preg_match('/[\x00-\x1f]/',$title))$title='prompt.wav';
        if(!move_uploaded_file($upload['tmp_name'],$path))throw new RuntimeException('The audio file could not be saved.');chmod($path,0600);
        try{$this->db->beginTransaction();$this->insert('v_pbx_media',['media_uuid'=>$id,'domain_uuid'=>$this->domain,'category'=>'prompts','source_path'=>'uploaded/'.$id.'.wav','file_path'=>$path,'title'=>$title]);$this->insert('v_recordings',['recording_uuid'=>uuid(),'domain_uuid'=>$this->domain,'recording_filename'=>$path,'recording_name'=>$title]);$this->db->commit();}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();unlink($path);throw $e;}return $id;
    }
    public function delete(string $type,string $key): void {
        $this->db->beginTransaction();try{$c=$this->config(true);$kind=['user'=>'users','queue'=>'queues','ring_group'=>'ring_groups','receptionist'=>'receptionists','outbound'=>'outbound_rules'][$type]??null;if(!$kind)throw new InvalidArgumentException('This item cannot be deleted from this page.');
            if($type==='user'){$r=$c['users'][$key]??null;$index=$key;}else [$index,$r]=$this->row($c[$kind],$key,$type==='outbound'?'rule_id':'number');if(!$r)throw new InvalidArgumentException('This item is not in your PBX.');$check=$c;if($kind==='users')unset($check[$kind][$key]);else unset($check[$kind][$index]);
            if($type==='user'&&$this->query('select 1 from v_pbx_hotel_rooms where domain_uuid=:d and number=:n',['d'=>$this->domain,'n'=>$key])->fetchColumn())throw new InvalidArgumentException('Remove this phone from Hotel Services first.');
            if(in_array($type,['user','queue'],true)&&$this->query("select 1 from v_pbx_jobs where domain_uuid=:d and ".($type==='queue'?'queue_number':'target_number')."=:n and state in ('waiting','starting','calling')",['d'=>$this->domain,'n'=>$key])->fetchColumn())throw new InvalidArgumentException('Finish or cancel pending calls for this item first.');
            $referenced=function($node)use(&$referenced,$key,$type): bool{if(!is_array($node))return false;if(isset($node['type'],$node['number'])&&(string)$node['number']===$key&&!in_array($node['type'],['None','EndCall','External'],true))return true;if($type==='user'&&isset($node['members']))foreach($node['members'] as $m)if((string)$m['number']===$key&&isset($node['timeout']))return true;foreach($node as $value)if(is_array($value)&&$referenced($value))return true;return false;};
            $pinReference=false;if($type==='user')foreach($c['scripts'] as $script)foreach($script['pin_map']??[] as $target)if((string)$target===$key)$pinReference=true;
            if($type!=='outbound'&&($referenced($check)||$pinReference))throw new InvalidArgumentException('This item is used by a call route or group. Change those destinations first.');
            if($type==='user'){$this->query('delete from v_voicemail_greetings where domain_uuid=:d and voicemail_id=:n',['d'=>$this->domain,'n'=>$key]);$this->query('delete from v_voicemail_messages where domain_uuid=:d and voicemail_uuid=:id',['d'=>$this->domain,'id'=>$r['voicemail_uuid']]);$this->query('delete from v_voicemails where domain_uuid=:d and voicemail_uuid=:id',['d'=>$this->domain,'id'=>$r['voicemail_uuid']]);$this->query('delete from v_extensions where domain_uuid=:d and extension_uuid=:id',['d'=>$this->domain,'id'=>$r['extension_uuid']]);unset($c['users'][$key]);}
            else{if($type==='queue'){$this->query('delete from v_call_center_tiers where domain_uuid=:d and call_center_queue_uuid=:id',['d'=>$this->domain,'id'=>$r['uuid']]);$this->query('delete from v_call_center_queues where domain_uuid=:d and call_center_queue_uuid=:id',['d'=>$this->domain,'id'=>$r['uuid']]);}elseif($type==='ring_group'){$this->query('delete from v_ring_group_destinations where domain_uuid=:d and ring_group_uuid=:id',['d'=>$this->domain,'id'=>$r['uuid']]);$this->query('delete from v_ring_groups where domain_uuid=:d and ring_group_uuid=:id',['d'=>$this->domain,'id'=>$r['uuid']]);}elseif($type==='receptionist'){$this->query('delete from v_ivr_menu_options where domain_uuid=:d and ivr_menu_uuid=:id',['d'=>$this->domain,'id'=>$r['uuid']]);$this->query('delete from v_ivr_menus where domain_uuid=:d and ivr_menu_uuid=:id',['d'=>$this->domain,'id'=>$r['uuid']]);}unset($c[$kind][$index]);$c[$kind]=array_values($c[$kind]);}
            if(!empty($r['dialplan_uuid'])){$this->query('delete from v_dialplan_details where domain_uuid=:d and dialplan_uuid=:id',['d'=>$this->domain,'id'=>$r['dialplan_uuid']]);$this->query('delete from v_dialplans where domain_uuid=:d and dialplan_uuid=:id',['d'=>$this->domain,'id'=>$r['dialplan_uuid']]);}
            if($type!=='outbound')foreach($c['departments'] as &$department)$department['members']=array_values(array_filter($department['members'],fn($m)=>(string)$m['number']!==$key));unset($department);$this->saveConfig($c);$this->db->commit();
        }catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}
        if($type==='user'){(new cache)->delete('directory:'.$r['auth_id'].'@'.$c['realm']);(new cache)->delete('directory:'.$key.'@'.$c['realm']);}
        $this->changed(null,$type==='queue'?$key:null);
    }
}
