<?php
/** Reader for the V20 Update 9 backup layout verified against the supplied private backup. */
final class threecx_v20 {
    private array $notes=[];
    private function children(?DOMElement $node,string $name=''): array { $out=[];if($node)foreach($node->childNodes as $child)if($child instanceof DOMElement && ($name===''||$child->tagName===$name))$out[]=$child;return $out; }
    private function child(?DOMElement $node,string $name): ?DOMElement { $rows=$this->children($node,$name);if(count($rows)>1)throw new InvalidArgumentException('The backup has duplicate settings.');return $rows[0]??null; }
    private function value(?DOMElement $node,string $name,string $default=''): string { $field=$this->child($node,$name);if(!$field)return $default;if($this->children($field))throw new InvalidArgumentException('The backup has an unexpected setting format.');$text=trim($field->textContent);if(strlen($text)>32768||preg_match('/[\x00-\x08\x0b\x0c\x0e-\x1f]/',$text))throw new InvalidArgumentException('A backup setting is too large.');return $text; }
    private function flag(string $value,bool $default=false): bool { if($value==='')return $default;return match(strtolower($value)){'true','1'=>true,'false','0'=>false,default=>throw new InvalidArgumentException('A backup switch is invalid.')}; }
    private function integer(string $value,int $default,int $min=0,int $max=86400): int { if($value==='')return $default;if(!ctype_digit($value)||(int)$value<$min||(int)$value>$max)throw new InvalidArgumentException('A backup number is invalid.');return (int)$value; }
    private function number(string $value,bool $special=false): string { if(!preg_match($special?'/^(?:[0-9]{1,10}|\*[0-9]{1,5}|SP[0-9]{1,3}|QCB|GRP[0-9]{1,10})$/D':'/^[0-9]{2,10}$/D',$value))throw new InvalidArgumentException('A backup extension is invalid.');return $value; }
    private function name(string $value,string $fallback=''): string { $value=$value?:$fallback;if(mb_strlen($value)>120||preg_match('/[\x00-\x1f]/',$value))throw new InvalidArgumentException('A backup name is invalid.');return $value; }
    private function properties(DOMElement $node): array { $out=[];foreach($this->children($this->child($node,'Properties')) as $property){$name=$this->value($property,'Name');if(isset($out[$name]))throw new InvalidArgumentException('The backup has repeated properties.');$out[$name]=$this->value($property,'Value');}return $out; }
    private function destination(?DOMElement $node): array {
        $type=$this->value($node,'To','None');$internal=$this->child($node,'Internal');$number=$internal?->getAttribute('DN')??'';$external=$this->value($node,'External');
        if(!in_array($type,['None','Extension','VoiceMail','RingGroup','Queue','IVR','External','Boomerang','RoutePoint','EndCall','Fax'],true))throw new InvalidArgumentException('The backup has a call destination that is not supported.');
        if($number!=='')$this->number($number,true);
        if($external!==''&&!preg_match('/^\+?[0-9*#]{1,32}$/D',$external))throw new InvalidArgumentException('A forwarding number is invalid.');
        return ['type'=>$type,'number'=>$number,'external'=>$external];
    }
    private function hours(?DOMElement $node): array {
        $type=$node?->getAttribute('HoursType')?:'AllHours';if(!in_array($type,['AllHours','OfficeHours','OutOfOfficeHours','SpecificHours','SpecificHoursExcludingHolidays'],true))throw new InvalidArgumentException('An office-hours setting is not supported.');
        $periods=[];$days=['Sunday'=>0,'Monday'=>1,'Tuesday'=>2,'Wednesday'=>3,'Thursday'=>4,'Friday'=>5,'Saturday'=>6];
        foreach($this->children($node,'PeriodsOfDay') as $day){$name=$day->getAttribute('DayOfWeek');if(!isset($days[$name]))throw new InvalidArgumentException('An office-hours day is invalid.');foreach($this->children($day,'PeriodOfDay') as $period){$start=$period->getAttribute('begin');$end=$period->getAttribute('end');foreach([$start,$end] as $time)if(!preg_match('/^(?:[01][0-9]|2[0-3]):[0-5][0-9](?::[0-5][0-9])?$/D',$time)&&!in_array($time,['24:00','24:00:00'],true))throw new InvalidArgumentException('An office-hours time is invalid.');$periods[]=['day'=>$days[$name],'start'=>substr($start,0,5),'end'=>substr($end,0,5)];}}
        return ['type'=>$type,'periods'=>$periods,'ignore_holidays'=>$this->flag($node?->getAttribute('IgnoreHolidays')??'')];
    }
    private function profiles(DOMElement $user): array {
        $out=[];foreach($this->children($this->child($user,'FwdProfiles'),'FwdProfile') as $profile){$name=$this->value($profile,'Name');$row=['name'=>$name,'timeout'=>$this->integer($this->value($profile,'NoAnswerTimeout'),20,1,600),'disable_ring_groups'=>$this->flag($this->value($profile,'DisableRingGroupCalls')),'ring_mobile'=>$this->flag($this->value($profile,'RingMyMobile')),'queue_status'=>$this->value($profile,'ForceQueueStatus','-1'),'busy_detection'=>$this->value($profile,'BusyDetection','UsePBXStatus'),'available'=>[],'away'=>[]];
            foreach(['NoAnswer','Busy','NotRegistered'] as $reason){$parent=$this->child($this->child($profile,'AvailableRoute'),$reason);if(!$parent)continue;$row['available'][$reason]=['internal_inactive'=>$this->flag($parent->getAttribute('InternalInactive')),'all'=>$this->destination($this->child($parent,'AllCalls')),'internal'=>$this->destination($this->child($parent,'Internal'))];}
            foreach(['Internal','External'] as $origin){$parent=$this->child($this->child($profile,'AwayRoute'),$origin);if(!$parent)continue;$row['away'][$origin]=['outside_inactive'=>$this->flag($parent->getAttribute('OutOfHoursInactive')),'all'=>$this->destination($this->child($parent,'AllHours')),'outside'=>$this->destination($this->child($parent,'OutOfOfficeHours'))];}
            $out[$name]=$row;
        }return $out;
    }
    private function objectHours(DOMElement $node): array { return ['hours'=>$this->hours($this->child($node,'Hours')),'breaks'=>$this->hours($this->child($node,'BreakTime')),'outside'=>$this->value($node,'OutOfOfficeHoursRoute'),'break'=>$this->value($node,'BreakTimeRoute'),'holiday'=>$this->value($node,'HolidaysRoute')]; }
    private function note(string $category,int $count,string $reason): void { if($count>0)$this->notes[]=['category'=>$category,'count'=>$count,'reason'=>$reason]; }
    public static function read(DOMElement $root): array {
        $reader=new self();return $reader->parse($root);
    }
    private function parse(DOMElement $root): array {
        $version=$this->value($this->child($root,'header'),'version');
        if($version!=='20.0.9.995')throw new InvalidArgumentException('This 3CX update needs a matching restore check.');
        $tenants=$this->children($this->child($root,'Tenants'),'Tenant');if(count($tenants)!==1)throw new InvalidArgumentException('Choose a backup with one company.');$tenant=$tenants[0];$dn=$this->child($tenant,'DN');
        $plan=['source_version'=>$version,'source_format'=>'3cx-v20-backup','supported'=>true,'users'=>[],'trunks'=>[],'ring_groups'=>[],'inbound_rules'=>[],'outbound_rules'=>[],'warnings'=>[],'unsupported'=>[]];
        $full=['users'=>[],'queues'=>[],'receptionists'=>[],'ring_groups'=>[],'departments'=>[],'inbound_rules'=>[],'outbound_rules'=>[],'phones'=>[],'contacts'=>[],'specials'=>[],'scripts'=>[],'trunks'=>[],'timezone'=>'Africa/Johannesburg','default_hours'=>$this->hours($this->child($tenant,'Hours'))];
        $parameters=[];foreach($this->children($this->child($root,'Parameters'),'Parameter') as $p)$parameters[$this->value($p,'Name')]=$this->value($p,'Value');
        // These source codes are retained alongside a selectable timezone; do not discard them.
        $full['timezone_code']=$parameters['TIMEZONE_GLOBAL_ID']??'';$full['timezone_offset']=$parameters['TIMEZONE_GLOBAL_ZONE']??'';
        $full['operator']=$parameters['OPERATOR']??'';$full['voicemail_number']=$parameters['VMAIL']??'999';
        $providers=[];foreach($this->children($this->child($root,'Gateways')) as $provider){$name=$this->value($provider,'Name');if($name===''||isset($providers[$name]))throw new InvalidArgumentException('A provider name is missing or repeated.');$providers[$name]=$provider;}
        foreach($this->children($this->child($tenant,'Groups'),'Group') as $group){$properties=$this->properties($group);$number=$this->number($this->value($group,'Number'),true);$members=[];foreach($this->children($this->child($group,'Members'),'Member') as $member)$members[]=['number'=>$this->number($member->getAttribute('DN'),true),'primary'=>$this->flag($member->getAttribute('IsPrimary'))];$full['departments'][]=['number'=>$number,'name'=>$this->name($this->value($group,'Name'),$number),'members'=>$members,'timezone_code'=>$properties['TIMEZONE']??$full['timezone_code'],'timezone'=>'Africa/Johannesburg','hours'=>$this->hours($this->child($group,'Hours')),'breaks'=>$this->hours($this->child($group,'BreakTime')),'mode'=>$this->value($group,'CallHandlingMode','0'),'holidays'=>[]];}
        foreach($this->children($dn) as $node){$kind=$node->tagName;$number=$this->number($this->value($node,'Number'),true);$properties=$this->properties($node);
            if($kind==='Extension'){
                $this->number($number);$name=$this->name(trim($this->value($node,'FirstName').' '.$this->value($node,'LastName')),$number);$email=$this->value($node,'EmailAddress');if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))throw new InvalidArgumentException('A user email address is invalid.');
                $plan['users'][]=['number'=>$number,'name'=>$name,'email'=>$email,'auth_id'=>$this->value($node,'AuthID',$number),'password'=>$this->value($node,'AuthPassword'),'voicemail_pin'=>$this->value($node,'VMPIN'),'enabled'=>$this->flag($this->value($node,'Enabled'),true)];
                $full['users'][$number]=['number'=>$number,'profile'=>$this->value($node,'CurrentProfile','Available'),'profiles'=>$this->profiles($node),'record_calls'=>$this->flag($this->value($node,'RecordCalls')),'voicemail_enabled'=>$this->flag($this->value($node,'VMEnabled'),true),'voicemail_email'=>$this->value($node,'VMEmailOptions','None'),'outbound_caller_id'=>$this->value($node,'OutboundCallerID'),'queue_status'=>$this->value($node,'QueueStatus','LoggedIn'),'mobile'=>$properties['MOBILENUMBER']??'','auto_status'=>$properties['OFFICEHOURSPROPERTIES']??'0','record_external_only'=>$this->flag($properties['RECORD_EXTERNAL_CALLS_ONLY']??'false'),'hours'=>$this->objectHours($node)];
                foreach($this->children($this->child($node,'PhoneDevices'),'PhoneDevice') as $phone){$mac=strtolower(preg_replace('/[^0-9a-f]/i','',$this->value($phone,'MAC')));if($mac!==''&&strlen($mac)!==12)throw new InvalidArgumentException('A phone address is invalid.');$full['phones'][]=['number'=>$number,'mac'=>$mac,'template'=>$this->value($phone,'TemplateFilename'),'interface'=>$this->value($phone,'Interface'),'settings'=>$this->value($phone,'Settings')];}
                foreach($this->children($this->child($node,'PhoneBookEntries'),'PhoneBookEntry') as $contact)$full['contacts'][]=['owner'=>$number,'first_name'=>$this->value($contact,'FirstName'),'last_name'=>$this->value($contact,'LastName'),'company'=>$this->value($contact,'CompanyName'),'phone'=>$this->value($contact,'PhoneNumber')];
            }elseif($kind==='ExternalLine'){
                $providerName=$this->value($node,'Gateway');$provider=$providers[$providerName]??null;if(!$provider)throw new InvalidArgumentException('A trunk has no provider.');$host=$this->value($provider,'Host');$providerType=$this->value($provider,'Type','Provider');$register=$this->value($provider,'RequireRegistrationFor','Nothing')!=='Nothing';
                if($host===''&&$providerType==='BridgeMaster'){$host='127.0.0.1';$this->note('Bridges',1,'The connection to another 3CX PBX needs to be set up again.');}
                $plan['trunks'][]=['source_id'=>$number,'name'=>$this->name($providerName,$number),'host'=>$host,'port'=>$this->integer($this->value($provider,'Port')?:'5060',5060,1,65535),'transport'=>'udp','username'=>$this->value($node,'AuthID'),'password'=>$this->value($node,'AuthPassword'),'register'=>$register,'enabled'=>false];
                $headers=[];foreach($this->children($this->child($provider,'ArrayOfOutboundParam'),'OutboundParam') as $header)$headers[$header->getAttribute('ParamName')]=$header->getAttribute('ValueName');
                $full['trunks'][$number]=['number'=>$number,'main_number'=>$this->value($node,'ExternalNumber'),'caller_id'=>$this->value($node,'OutboundCallerID')?:($properties['OUTBOUNDCALLERID']??''),'dids'=>$this->value($node,'DIDNumbers'),'limit'=>$this->integer($this->value($node,'SimultaneousCalls'),10,1,10000),'expires'=>$this->integer($this->value($provider,'TimeBetweenReg'),3600,1,86400),'type'=>$providerType,'headers'=>$headers,'source_field'=>$this->value($provider,'SIPFieldWithDID','ToUserPart')];
                foreach($this->children($this->child($node,'RoutingRules'),'ExternalLineRule') as $index=>$rule){$conditions=$this->child($rule,'Conditions');$condition=$this->child($conditions,'Condition')?->getAttribute('Type');if(!in_array($condition,['ForwardAll','BasedOnDID'],true))throw new InvalidArgumentException('An incoming rule needs a restore update.');$destinations=$this->child($rule,'ForwardDestinations');$full['inbound_rules'][]=['trunk_id'=>$number,'order'=>$index,'name'=>$this->name($this->value($rule,'RuleName'),$number.' incoming calls'),'condition'=>$condition,'number'=>$this->value($rule,'Data'),'hours'=>$this->hours($this->child($rule,'Hours')),'office'=>$this->destination($this->child($destinations,'OfficeHoursDestination')),'outside'=>$this->destination($this->child($destinations,'OutOfOfficeHoursDestination')),'holiday'=>$this->destination($this->child($destinations,'HolidaysDestination')),'use_outside'=>$this->flag($this->value($destinations,'AlterDestinationDuringOutOfOfficeHours')),'use_holiday'=>$this->flag($this->value($destinations,'AlterDestinationDuringHolidays'))];}
            }elseif(in_array($kind,['Queue','RingGroup'],true)){
                $members=[];foreach($this->children($this->child($node,'Members'),'Member') as $member)$members[]=['number'=>$this->number($member->getAttribute('DN')),'status'=>$member->getAttribute('QueueStatus')?:'LoggedIn','skill'=>$member->getAttribute('SkillGroup')?:'0'];
                $row=['number'=>$number,'name'=>$this->name($this->value($node,'Name'),$number),'members'=>$members,'destination'=>$this->destination($this->child($node,'Destination')),'hours'=>$this->objectHours($node)];
                if($kind==='Queue'){$row+=['strategy'=>$this->value($node,'PollingStrategy','RingAll'),'timeout'=>$this->integer($this->value($node,'MasterTimeout'),1800,1,86400),'ring_timeout'=>$this->integer($this->value($node,'RingTimeout'),30,1,600),'intro'=>$this->flag($this->value($node,'EnableIntro'))?$this->value($node,'IntroFile'):'','moh'=>$this->value($node,'OnHoldFile'),'announce_position'=>$this->flag($this->value($node,'AnnounceQueuePosition')),'announce_interval'=>$this->integer($this->value($node,'AnnouncementInterval'),30,0,86400),'wrap_up'=>$this->integer($properties['WRAPUP_TIME']??'',2,0,600),'callback'=>$properties['CALLBACK_ENABLE_TIME']??'-1'];$row['callback_mode']=(int)$row['callback']<0?'disabled':((int)$row['callback']===0?'request':(($properties['CALLBACK_OFFER_ONLY']??'0')==='1'?'offer':'automatic'));$row['callback_after']=max(1,(int)$row['callback']);$row['callback_prefix']='';$row['callback_attempts']=3;$full['queues'][]=$row;}
                else{$row+=['strategy'=>$this->value($node,'RingStrategy','RingAll'),'timeout'=>$this->integer($this->value($node,'RingTime'),30,1,600)];$full['ring_groups'][]=$row;}
            }elseif($kind==='IVR'){
                $options=[];foreach($this->children($this->child($node,'Forwards'),'IVRForward') as $option){$digit=$this->value($option,'Number');if(!preg_match('/^[0-9*#]{1,10}$/D',$digit))throw new InvalidArgumentException('A receptionist key is invalid.');$options[]=['digit'=>$digit,'destination'=>['type'=>$this->value($option,'ForwardType','EndCall'),'number'=>$this->value($option,'ForwardDN'),'external'=>$this->value($option,'CustomData')]];}
                $full['receptionists'][]=['number'=>$number,'name'=>$this->name($this->value($node,'Name'),$number),'prompt'=>$this->value($node,'PromptFilename'),'timeout'=>$this->integer($this->value($node,'Timeout'),15,1,600),'timeout_destination'=>['type'=>$this->value($node,'TimeoutForwardType','EndCall'),'number'=>$this->value($node,'TimeoutForwardDN'),'external'=>''],'options'=>$options,'hours'=>$this->objectHours($node)];
            }elseif($kind==='RoutePoint'){
                $script=$this->value($node,'ScriptCode');$map=[];
                if(str_contains($script,'UserInputIVRSample')&&str_contains($script,'UserInputMap[userInput]')){if(preg_match('/UserInputMap\s*=.*?\{(.*?)\};/s',$script,$matches))foreach(preg_match_all('/\{\s*"([0-9]{1,12})"\s*,\s*"([0-9]{2,10})"\s*\}/',$matches[1],$pairs,PREG_SET_ORDER)?$pairs:[] as $pair)$map[$pair[1]]=$pair[2];}
                if(!$map)$this->note('Call Scripts',1,'This call script needs to be recreated before it can answer calls.');
                $full['scripts'][]=['number'=>$number,'name'=>$properties['CF_APP_NAME']??$number,'kind'=>$map?'pin_menu':'unavailable','pin_map'=>$map,'attempts'=>3,'timeout'=>10,'interdigit_timeout'=>2];
            }else{$full['specials'][]=['number'=>$number,'kind'=>$kind];}
        }
        foreach($this->children($this->child($tenant,'OutboundRules'),'OutboundRule') as $index=>$rule){$routes=[];foreach($this->children($this->child($rule,'OutboundRoutes'),'OutboundRoute') as $route){$gateway=$this->value($route,'Gateway');if($gateway==='')continue;$routes[]=['provider'=>$gateway,'strip'=>$this->integer($this->value($route,'StripDigits'),0,0,20),'prepend'=>$this->value($route,'Prepend'),'caller_id'=>$this->value($route,'CallerID')];}$groups=[];foreach($this->children($this->child($rule,'DNGroups'),'Group') as $group)$groups[]=trim($group->textContent);$ranges=[];foreach($this->children($this->child($rule,'DNRanges'),'DNRange') as $range)$ranges[]=['from'=>$this->value($range,'From'),'to'=>$this->value($range,'To')];$full['outbound_rules'][]=['name'=>$this->name($this->value($rule,'Name'),'Outbound rule'),'prefix'=>$this->value($rule,'Prefix'),'lengths'=>$this->value($rule,'NumberLengthRanges'),'priority'=>$this->integer($this->value($rule,'Priority'),$index,0,2147483647),'routes'=>$routes,'departments'=>$groups,'ranges'=>$ranges];}
        usort($full['outbound_rules'],fn($a,$b)=>$a['priority']<=>$b['priority']);
        $this->note('3CX apps and account passwords',1,'Users and phone details are restored. 3CX apps and old web passwords cannot be used here; phones need the new server address.');
        if($this->value($this->child($root,'mailSettings'),'mailServerType')==='3CX')$this->note('Email',1,'The backup uses 3CX email delivery. Set your outgoing email server under System → Email.');
        $known=array_keys($full['users']);foreach(['queues','receptionists','ring_groups','scripts','specials'] as $key)foreach($full[$key] as $r)$known[]=$r['number'];$missing=0;foreach($full['scripts'] as $r)foreach($r['pin_map'] as $n)if(!in_array((string)$n,array_map('strval',$known),true))$missing++;$this->note('Call Scripts',$missing,'The original PIN menu has destinations that are missing from this backup. Choose replacement users under Call Handling.');$plan['v20']=$full;$plan['unsupported']=$this->notes;$plan['warnings'][]='Users, phone settings, call handling and office hours will be restored to a new PBX. Trunks stay off until their connection is checked.';
        return $plan;
    }
    public static function counts(array $plan): array { $v=$plan['v20']??[];return ['users'=>count($plan['users']??[]),'trunks'=>count($plan['trunks']??[]),'departments'=>count($v['departments']??[]),'queues'=>count($v['queues']??[]),'receptionists'=>count($v['receptionists']??[]),'ring_groups'=>count($v['ring_groups']??[]),'inbound_rules'=>count($v['inbound_rules']??[]),'outbound_rules'=>count($v['outbound_rules']??[]),'phones'=>count($v['phones']??[])]; }
}
