/* OpenWeb PBX isolated codec callbacks; no engine, SIP or customer data.
 * Compile with OPENWEB_BCG729_SOURCE pointing to the reviewed patched module.
 * This test includes that MPL 1.1 module; retain its original license/notices.
 */
#define _GNU_SOURCE
#include <assert.h>
#include <math.h>
#include <stdio.h>
#ifndef OPENWEB_BCG729_SOURCE
#error Define OPENWEB_BCG729_SOURCE to the patched mod_bcg729.c path
#endif
#include OPENWEB_BCG729_SOURCE

static unsigned checks;
#define CHECK(condition) do { assert(condition); checks++; } while (0)
static int untouched(const void *data, size_t size) {
    const uint8_t *p = data;
    while (size--) if (*p++ != 0x5a) return 0;
    return 1;
}

int main(void) {
    struct bcg729_context context = {0};
    switch_codec_t codec = {0};
    switch_codec_implementation_t implementation = {0};
    int16_t input[960], decoded[960];
    uint8_t encoded[120], sid[10], mixed[12];
    uint32_t encoded_length, decoded_length, rate;
    unsigned flags = 0, packet, i;
    double energy = 0;
    uint8_t sid_length = 0;
    bcg729EncoderChannelContextStruct *vad;
    context.encoder_object = initBcg729EncoderChannel(0);
    context.decoder_object = initBcg729DecoderChannel();
    CHECK(context.encoder_object && context.decoder_object);
    codec.private_info = &context;
    implementation.samples_per_packet = 160;
    codec.implementation = &implementation;

    /* One second of a deterministic 440 Hz signal, 20 ms packets. */
    for (packet = 0; packet < 50; packet++) {
        for (i = 0; i < 160; i++) input[i] = (int16_t)(10000 * sin(2 * 3.141592653589793 * 440 * (packet * 160 + i) / 8000));
        encoded_length = sizeof(encoded); rate = 0;
        assert(switch_bcg729_encode(&codec, NULL, input, 320, 8000, encoded, &encoded_length, &rate, &flags) == SWITCH_STATUS_SUCCESS);
        assert(encoded_length == 20 && rate == 8000);
        decoded_length = sizeof(decoded); rate = 0;
        assert(switch_bcg729_decode(&codec, NULL, encoded, encoded_length, 8000, decoded, &decoded_length, &rate, &flags) == SWITCH_STATUS_SUCCESS);
        assert(decoded_length == 320 && rate == 8000);
        for (i = 0; i < 160; i++) energy += (double)decoded[i] * decoded[i];
    }
    CHECK(energy / 8000 > 1000000);
    /* Largest registered 120 ms packet: all twelve frames are preserved. */
    for (i = 0; i < 960; i++) input[i] = (int16_t)(i % 100 * 100);
    encoded_length = sizeof(encoded);
    CHECK(switch_bcg729_encode(&codec, NULL, input, sizeof(input), 8000, encoded, &encoded_length, &rate, &flags) == SWITCH_STATUS_SUCCESS && encoded_length == 120);
    decoded_length = sizeof(decoded);
    CHECK(switch_bcg729_decode(&codec, NULL, encoded, encoded_length, 8000, decoded, &decoded_length, &rate, &flags) == SWITCH_STATUS_SUCCESS && decoded_length == sizeof(decoded));

    memset(encoded, 0x5a, sizeof(encoded)); encoded_length = 9;
    CHECK(switch_bcg729_encode(&codec, NULL, input, 160, 8000, encoded, &encoded_length, &rate, &flags) == SWITCH_STATUS_FALSE && untouched(encoded, sizeof(encoded)));
    encoded_length = sizeof(encoded);
    CHECK(switch_bcg729_encode(&codec, NULL, input, 159, 8000, encoded, &encoded_length, &rate, &flags) == SWITCH_STATUS_FALSE && untouched(encoded, sizeof(encoded)));
    CHECK(switch_bcg729_encode(&codec, NULL, input, 160, 16000, encoded, &encoded_length, &rate, &flags) == SWITCH_STATUS_FALSE && untouched(encoded, sizeof(encoded)));
    memset(decoded, 0x5a, sizeof(decoded)); decoded_length = 159;
    CHECK(switch_bcg729_decode(&codec, NULL, encoded, 10, 8000, decoded, &decoded_length, &rate, &flags) == SWITCH_STATUS_FALSE && untouched(decoded, sizeof(decoded)));
    for (i = 1; i < 20; i++) if (i % 10 != 0 && i % 10 != 2) {
        decoded_length = sizeof(decoded);
        assert(switch_bcg729_decode(&codec, NULL, encoded, i, 8000, decoded, &decoded_length, &rate, &flags) == SWITCH_STATUS_FALSE);
        assert(untouched(decoded, sizeof(decoded)));
    }
    checks++;

    /* Loss concealment returns the full native packet, with pre-write bounds. */
    decoded_length = 319;
    CHECK(switch_bcg729_decode(&codec, NULL, NULL, 0, 8000, decoded, &decoded_length, &rate, &flags) == SWITCH_STATUS_FALSE && untouched(decoded, sizeof(decoded)));
    decoded_length = sizeof(decoded); rate = 0;
    CHECK(switch_bcg729_decode(&codec, NULL, NULL, 0, 8000, decoded, &decoded_length, &rate, &flags) == SWITCH_STATUS_SUCCESS && decoded_length == 320 && rate == 8000);

    /* Decode a SID generated by the real library's VAD, then mixed speech/SID. */
    vad = initBcg729EncoderChannel(1); assert(vad);
    memset(input, 0, 160);
    for (i = 0; i < 200 && sid_length != 2; i++) bcg729Encoder(vad, input, sid, &sid_length);
    CHECK(sid_length == 2);
    decoded_length = sizeof(decoded);
    CHECK(switch_bcg729_decode(&codec, NULL, sid, 2, 8000, decoded, &decoded_length, &rate, &flags) == SWITCH_STATUS_SUCCESS && decoded_length == 160);
    encoded_length = sizeof(encoded);
    assert(switch_bcg729_encode(&codec, NULL, input, 160, 8000, encoded, &encoded_length, &rate, &flags) == SWITCH_STATUS_SUCCESS);
    memcpy(mixed, encoded, 10); memcpy(mixed + 10, sid, 2);
    decoded_length = sizeof(decoded);
    CHECK(switch_bcg729_decode(&codec, NULL, mixed, sizeof(mixed), 8000, decoded, &decoded_length, &rate, &flags) == SWITCH_STATUS_SUCCESS && decoded_length == 320);
    memset(decoded, 0x5a, sizeof(decoded)); decoded_length = 319;
    CHECK(switch_bcg729_decode(&codec, NULL, mixed, sizeof(mixed), 8000, decoded, &decoded_length, &rate, &flags) == SWITCH_STATUS_FALSE && untouched(decoded, sizeof(decoded)));
    closeBcg729EncoderChannel(vad);
    CHECK(switch_bcg729_destroy(&codec) == SWITCH_STATUS_SUCCESS && !codec.private_info);
    CHECK(switch_bcg729_destroy(&codec) == SWITCH_STATUS_SUCCESS);
    printf("PASS: %u native bcg729 encode/decode/frame/VAD/PLC/buffer checks\n", checks);
    return 0;
}
