<?php
/** Synthetic V20 trunk preservation checks; no carrier connections or user backup. */
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
require dirname(__DIR__).'/resources/require.php';
$checks=0;$check=function(bool $ok,string $label)use(&$checks){if(!$ok)throw new RuntimeException($label);$checks++;};
$reject=function(callable $fn,string $label)use($check){try{$fn();}catch(InvalidArgumentException){$check(true,$label);return;}$check(false,$label);};
$xml=<<<'XML'
<PhoneSystem><header><version>20.0.9.995</version></header><Gateways>
<Gateway><Name>Registered fixture</Name><Type>Provider</Type><Host>sip.example.invalid</Host><Port>5080</Port><TransportProtocol>tcp</TransportProtocol><RequireRegistrationFor>InOutCalls</RequireRegistrationFor><TimeBetweenReg>180</TimeBetweenReg><Realm>provider.example.invalid</Realm><ProxyHost>proxy.example.invalid</ProxyHost><ProxyPort>5070</ProxyPort><SIPFieldWithDID Name="RequestLineURIUser"/><Codecs><codec RFCName="PCMA"/><codec RFCName="PCMU"/></Codecs><ArrayOfOutboundParam><OutboundParam ParamName="FromUserPart" ValueName="$AuthID"/><OutboundParam ParamName="FromHostPart" ValueName="$GWHostPort"/><OutboundParam ParamName="ContactUser" ValueName="$AuthID"/><OutboundParam ParamName="RemotePartyIDCallingPartyUserPart" ValueName="$OutboundCallerId"/></ArrayOfOutboundParam></Gateway>
<Gateway><Name>Digest without REGISTER fixture</Name><Type>Provider</Type><Host>sip2.example.invalid</Host><Port>0</Port><RequireRegistrationFor>Nothing</RequireRegistrationFor><TimeBetweenReg>600</TimeBetweenReg><SIPFieldWithDID Name="ToUserPart"/><Codecs><codec RFCName="G729"/><codec RFCName="PCMU"/></Codecs><ArrayOfOutboundParam><OutboundParam ParamName="FromUserPart" ValueName="$OutboundCallerId"/><OutboundParam ParamName="FromHostPart" ValueName="$GWHostPort"/></ArrayOfOutboundParam></Gateway>
<Gateway><Name>IP fixture</Name><Type>Provider</Type><Host>2001:db8::5</Host><Port>5061</Port><TransportProtocol>tls</TransportProtocol><RequireRegistrationFor>Nothing</RequireRegistrationFor><SIPFieldWithDID Name="ToUserPart"/><Codecs><codec RFCName="PCMA"/></Codecs></Gateway>
</Gateways><Tenants><Tenant><DN>
<ExternalLine><Number>10000</Number><Gateway>Registered fixture</Gateway><AuthID>fixtureuser</AuthID><AuthPassword>fixture-password</AuthPassword><ExternalNumber>12025550100</ExternalNumber><OutboundCallerID>12025550100</OutboundCallerID><SimultaneousCalls>25</SimultaneousCalls><Properties><Property><Name>USESEPARATEAUTHID</Name><Value>1</Value></Property><Property><Name>SEPARATEAUTHID</Name><Value>fixtureauth</Value></Property></Properties><RoutingRules><ExternalLineRule><RuleName>Suffix</RuleName><Conditions><Condition Type="BasedOnDID"/></Conditions><Data>*5550100</Data><ForwardDestinations><OfficeHoursDestination><To>None</To></OfficeHoursDestination></ForwardDestinations></ExternalLineRule></RoutingRules></ExternalLine>
<ExternalLine><Number>10001</Number><Gateway>Digest without REGISTER fixture</Gateway><AuthID>digestuser</AuthID><AuthPassword>digest-password</AuthPassword><ExternalNumber>12025550101</ExternalNumber><SimultaneousCalls>12</SimultaneousCalls><Properties><Property><Name>OUTBOUNDCALLERID</Name><Value>&lt;Rules/&gt;</Value></Property></Properties><RoutingRules><ExternalLineRule><RuleName>Exact</RuleName><Conditions><Condition Type="BasedOnDID"/></Conditions><Data>+12025550101</Data><ForwardDestinations><OfficeHoursDestination><To>None</To></OfficeHoursDestination></ForwardDestinations></ExternalLineRule></RoutingRules></ExternalLine>
<ExternalLine><Number>10002</Number><Gateway>IP fixture</Gateway><ExternalNumber>12025550102</ExternalNumber><RoutingRules><ExternalLineRule><RuleName>Default</RuleName><Conditions><Condition Type="ForwardAll"/></Conditions><ForwardDestinations><OfficeHoursDestination><To>None</To></OfficeHoursDestination></ForwardDestinations></ExternalLineRule></RoutingRules></ExternalLine>
</DN></Tenant></Tenants></PhoneSystem>
XML;
$parse=function(string $raw){$d=new DOMDocument();$d->loadXML($raw,LIBXML_NONET|LIBXML_NOBLANKS);return threecx_v20::read($d->documentElement);};
$plan=$parse($xml);pbx_v20_restore::validate($plan);
$check($plan['trunks'][0]['register']&&!$plan['trunks'][1]['register'],'REGISTER behavior preserved independently');
$check($plan['v20']['trunks']['10001']['auth_mode']==='credentials'&&$plan['v20']['trunks']['10002']['auth_mode']==='ip','Digest without REGISTER and pure IP are distinct');
$check($plan['trunks'][1]['port']===5060,'Source port zero uses SIP default');
$check($plan['v20']['trunks']['10001']['caller_id']===''&&$plan['v20']['trunks']['10001']['caller_id_rules']==='<Rules/>','Formatting XML is never used as caller ID');
$check($plan['v20']['trunks']['10000']['source_field']==='RequestLineURIUser','DID Name attribute is retained');
$check($plan['v20']['trunks']['10000']['codecs']===['PCMA','PCMU'],'Provider codec preference order retained');
$native=pbx_v20_restore::gatewaySettings(array_merge($plan['v20']['trunks']['10000'],$plan['trunks'][0]));
$check($native['username']==='fixtureuser'&&$native['auth_username']==='fixtureauth'&&$native['password']==='fixture-password','Separate SIP authentication ID retained');
$check($native['from_user']==='fixtureuser'&&$native['from_domain']==='sip.example.invalid:5080','Source From symbolic fields mapped');
$check($native['register_proxy']==='proxy.example.invalid:5070'&&$native['outbound_proxy']==='proxy.example.invalid:5070','Registrar and outbound proxy retained');
$check($native['realm']==='provider.example.invalid'&&$native['register_transport']==='tcp','SIP realm and transport retained');
$check($native['extension']==='fixtureuser'&&$native['extension_in_contact']==='true'&&$native['sip_cid_type']==='rpid','Static Contact and RPID mapped');
$check($native['expire_seconds']===180&&$native['channels']===25&&$native['codec_prefs']==='PCMA,PCMU','Expiry concurrency and codec order retained');
$digest=pbx_v20_restore::gatewaySettings(array_merge($plan['v20']['trunks']['10001'],$plan['trunks'][1]));
$check(!$digest['register']&&$digest['username']==='digestuser'&&$digest['password']==='digest-password'&&$digest['caller_id_in_from'],'Challenge credentials preserved without REGISTER');
$ip=pbx_v20_restore::gatewaySettings(array_merge($plan['v20']['trunks']['10002'],$plan['trunks'][2],['username'=>'stale','password'=>'stale']));
$check($ip['proxy']==='[2001:db8::5]:5061'&&!$ip['register']&&$ip['username']===''&&$ip['password']===''&&$ip['auth_username']==='','Pure IP clears credentials and normalizes IPv6');
$check(pbx_v20_restore::incomingCondition($plan['v20']['inbound_rules'][0],$plan['v20']['trunks']['10000'])===['${sip_req_user}','^\+?[0-9]*5550100$'],'Suffix DID matches original Request URI field');
$check(pbx_v20_restore::incomingCondition($plan['v20']['inbound_rules'][1],$plan['v20']['trunks']['10001'])===['${sip_to_user}','^\+?12025550101$'],'Exact DID matches original To field');
$check(pbx_v20_restore::incomingCondition($plan['v20']['inbound_rules'][2],$plan['v20']['trunks']['10002'])===['${sip_to_user}','^\+?12025550102$'],'ForwardAll has source-aware condition');
$fallback=pbx_v20_restore::incomingCondition($plan['v20']['inbound_rules'][2],$plan['v20']['trunks']['10002'])[1];$check(preg_match('~'.$fallback.'~D','12025550102')===1&&preg_match('~'.$fallback.'~D','+12025550102')===1&&preg_match('~'.$fallback.'~D','12025550101')===0,'Fallback accepts only its own declared number with optional plus');
$fallback=pbx_v20_restore::incomingCondition(['condition'=>'ForwardAll'],['main_number'=>'00123','dids'=>"+12025550103;*550104\n00123"])[1];$check(preg_match('~'.$fallback.'~D','00123')===1&&preg_match('~'.$fallback.'~D','123')===0&&preg_match('~'.$fallback.'~D','12025550103')===1&&preg_match('~'.$fallback.'~D','12025550104')===1&&preg_match('~'.$fallback.'~D','unrelated550104')===0,'Declared fallback list retains leading zeros and numeric suffix matching');
$check(pbx_v20_restore::incomingCondition(['condition'=>'ForwardAll'],[])===['${sip_to_user}','^(?!)$'],'A provider without declared numbers has no public fallback');
$check(pbx_v20_restore::incomingOrder(['condition'=>'BasedOnDID','number'=>'12025550101'],2)<pbx_v20_restore::incomingOrder(['condition'=>'BasedOnDID','number'=>'*5550101'],0)&&pbx_v20_restore::incomingOrder(['condition'=>'BasedOnDID','number'=>'*5550101'],2)<pbx_v20_restore::incomingOrder(['condition'=>'ForwardAll'],0),'Exact numbers precede suffixes and provider fallback');
$own='11111111-1111-4111-8111-111111111111';$other='22222222-2222-4222-8222-222222222222';[$bindingField,$bindingExpression]=pbx_v20_restore::incomingGatewayCondition(['gateway_uuid'=>$own]);$check($bindingField==='${sip_gateway}'&&preg_match('~'.$bindingExpression.'~D','')===1&&preg_match('~'.$bindingExpression.'~D',$own)===1&&preg_match('~'.$bindingExpression.'~D',$other)===0,'Native binding permits public unbound ingress and this provider only');
$reject(fn()=>pbx_v20_restore::incomingGatewayCondition(['gateway_uuid'=>'unsafe']),'An unsafe incoming native binding is rejected');
$safe=json_encode(threecx_backup::preview($plan));foreach(['fixture-password','digest-password','fixtureauth','fixtureuser','digestuser'] as $secret)$check(!str_contains($safe,$secret),'Preview remains credential-free');
$reject(fn()=>$parse(str_replace('Name="RequestLineURIUser"','Name="ContactUser"',$xml)),'Unsupported DID source fails closed');
$reject(fn()=>$parse(str_replace('RFCName="PCMA"','RFCName="UNKNOWN"',$xml)),'Unknown codec fails closed');
$base=array_merge($plan['v20']['trunks']['10000'],$plan['trunks'][0]);
foreach([['register_proxy'=>'proxy.invalid/evil'],['outbound_proxy'=>'https://proxy.invalid'],['from_user'=>'unsafe${expr}'],['realm'=>"bad\nrealm"],['codecs'=>['PCMA,PCMU']],['port'=>0],['expires'=>0],['limit'=>0],['auth_mode'=>'ip','register'=>true],['sip_cid_type'=>'evil']] as $mutation)$reject(fn()=>pbx_v20_restore::gatewaySettings(array_merge($base,$mutation)),'Unsafe provider setting fails closed');
$overrides=pbx_v20_restore::gatewaySettings(array_merge($base,['from_user'=>'override','from_domain'=>'from.example.invalid','contact_user'=>'contact','caller_id_in_from'=>true,'sip_cid_type'=>'pid','codecs'=>['G722']]));
$check($overrides['from_user']==='override'&&$overrides['from_domain']==='from.example.invalid'&&$overrides['extension']==='contact'&&$overrides['caller_id_in_from']&&$overrides['sip_cid_type']==='pid','Editor overrides take precedence over source header defaults');
$db=$database->db;$schema='openweb_trunk_test_'.bin2hex(random_bytes(6));
try {
 $db->exec('create schema '.$schema);$db->exec('set search_path to '.$schema.',public');
 foreach(['v_domains','v_extensions','v_voicemails','v_gateways','v_dialplans','v_dialplan_details','v_destinations','v_voicemail_greetings'] as $table)$db->exec('create table '.$table.' (like public.'.$table.' including all)');
 $db->exec(file_get_contents(dirname(__DIR__).'/app/pbx_setup/resources/restore.sql'));
 $domain=uuid();$realm='trunk-fixture.example.invalid';$db->beginTransaction();$s=$db->prepare('insert into v_domains(domain_uuid,domain_name,domain_enabled) values(?,?,true)');$s->execute([$domain,$realm]);
 (new pbx_setup_provisioner($db))->apply($domain,$realm,$plan);(new pbx_v20_restore($db))->apply($domain,$realm,$plan);
 $rows=$db->query('select * from v_gateways order by gateway')->fetchAll(PDO::FETCH_ASSOC);$byName=[];foreach($rows as $row)$byName[$row['gateway']]=$row;
 $r=$byName['Registered fixture'];$check($r['auth_username']==='fixtureauth'&&$r['realm']==='provider.example.invalid'&&$r['register_proxy']==='proxy.example.invalid:5070'&&$r['codec_prefs']==='PCMA,PCMU','Native SQL persists complete provider settings');
 $r=$byName['Digest without REGISTER fixture'];$check(!$r['register']&&$r['username']==='digestuser'&&$r['password']==='digest-password'&&$r['caller_id_in_from'],'Native SQL preserves digest credentials without REGISTER');
 $check(!$db->query('select bool_or(enabled) from v_gateways')->fetchColumn(),'Every imported trunk remains disabled');
 $check(!$db->query('select bool_or(destination_enabled) from v_destinations')->fetchColumn(),'Every incoming number remains disabled');
 $condition=$db->query("select dialplan_xml from v_dialplans where dialplan_number='*5550100'")->fetchColumn();$check(str_contains($condition,'${sip_req_user}')&&str_contains($condition,'^\+?[0-9]*5550100$'),'Stored XML preserves suffix and source field');
 $doc=new DOMDocument();$doc->loadXML($condition,LIBXML_NONET);$check($doc->getElementsByTagName('condition')->item(0)->getAttribute('field')==='${sip_gateway}','Native gateway condition precedes all number actions');
 $check($db->query("select count(*) from v_dialplan_details where dialplan_detail_type='\${sip_req_user}' and dialplan_detail_data='^\\+?[0-9]*5550100$'")->fetchColumn()==1,'Native dialplan details match XML source selection');
 $check($db->inTransaction(),'Trunk restore preserves caller-owned transaction');
 $stored=json_decode($db->query('select config from v_pbx_restore')->fetchColumn(),true);$stored['trunks']['10000']['allowed_ips']=['192.0.2.5'];$stored['trunks']['10000']['enabled']=true;unset($stored['trunks']['10000']['codecs']);$stored['trunks']['10000']['source_field']='';
 $s=$db->prepare('update v_pbx_restore set config=?');$s->execute([json_encode($stored)]);$db->exec("update v_gateways set codec_prefs=null,from_domain='old.example.invalid',extension_in_contact=null where gateway='Registered fixture'");$db->exec("update v_gateways set enabled=true where gateway='Registered fixture'");
 $legacy=$stored['inbound_rules'][0]['dialplan_uuid'];$doc->documentElement->removeChild($doc->getElementsByTagName('condition')->item(0));$s=$db->prepare('update v_dialplans set dialplan_xml=? where dialplan_uuid=?');$s->execute([$doc->saveXML($doc->documentElement),$legacy]);$s=$db->prepare("delete from v_dialplan_details where dialplan_uuid=? and dialplan_detail_type='\${sip_gateway}'");$s->execute([$legacy]);
 $refresh=new pbx_v20_restore($db);$before=$db->query('select config from v_pbx_restore')->fetchColumn();$dry=$refresh->refreshTrunks($domain,$plan,true);$check($dry['gateways_changed']===1&&$dry['policy_field_changes']['codecs']===1,'Reconciliation dry run identifies actual differences');
 $check($db->query('select config from v_pbx_restore')->fetchColumn()===$before&&$db->query("select codec_prefs from v_gateways where gateway='Registered fixture'")->fetchColumn()===null,'Dry run performs no writes');
 $check($dry['incoming_bindings_changed']===1&&$dry['incoming_details_inserted']===1,'Dry run identifies missing native gateway dispatch gate');
 $refresh->refreshTrunks($domain,$plan,false);$restored=json_decode($db->query('select config from v_pbx_restore')->fetchColumn(),true);$check($restored['trunks']['10000']['enabled']===true&&$restored['trunks']['10000']['allowed_ips']===['192.0.2.5'],'Reconciliation preserves operational enabled and IP-binding state');
 $check($restored['trunks']['10000']['gateway_uuid']===$stored['trunks']['10000']['gateway_uuid']&&$restored['users']===$stored['users'],'Reconciliation preserves native identity and all users');
 $s=$db->prepare("select count(*) from v_dialplan_details where dialplan_uuid=? and dialplan_detail_type='\${sip_gateway}'");$s->execute([$legacy]);$check((int)$s->fetchColumn()===1,'Reconciliation inserts missing native gateway condition atomically');
 $again=$refresh->refreshTrunks($domain,$plan,true);$check($again['gateways_changed']===0&&$again['policy_field_changes']===[]&&$again['incoming_xml_changed']===0&&$again['incoming_details_changed']===0,'Reconciliation is idempotent');
 $db->exec("update v_gateways set proxy='changed.example.invalid:5060' where gateway='Registered fixture'");$reject(fn()=>$refresh->refreshTrunks($domain,$plan,false),'Unexpected provider identity changes require explicit guard');
 $check($db->query('select config from v_pbx_restore')->fetchColumn()===json_encode($restored) || json_decode($db->query('select config from v_pbx_restore')->fetchColumn(),true)===$restored,'Rejected reconciliation performs no earlier policy writes');
 $db->exec("update v_gateways set proxy='sip.example.invalid:5080' where gateway='Registered fixture'");
 $customized=$restored;$customized['trunks']['10000']['codecs']=['G722'];$s=$db->prepare('update v_pbx_restore set config=?');$s->execute([json_encode($customized)]);$reject(fn()=>$refresh->refreshTrunks($domain,$plan,false),'Customized provider behavior is not silently overwritten');$s->execute([json_encode($restored)]);
 $foreign=uuid();$s=$db->prepare('update v_gateways set domain_uuid=? where gateway=?');$s->execute([$foreign,'Registered fixture']);$reject(fn()=>$refresh->refreshTrunks($domain,$plan,false),'A foreign native gateway is rejected');$s->execute([$domain,'Registered fixture']);
 $db->exec("update v_gateways set codec_prefs=null where gateway='Registered fixture'");$s->execute([$foreign,'IP fixture']);$reject(fn()=>$refresh->refreshTrunks($domain,$plan,false),'Late native mapping failure rejects entire reconciliation');$check($db->query("select codec_prefs from v_gateways where gateway='Registered fixture'")->fetchColumn()===null,'Late failure performs no earlier native correction');$s->execute([$domain,'IP fixture']);$refresh->refreshTrunks($domain,$plan,false);
 $reject(fn()=>$refresh->refreshTrunks(uuid(),$plan,false),'A foreign PBX without matching restore is rejected');
 $generic=['users'=>[],'trunks'=>[['source_id'=>'advanced','name'=>'Advanced setup fixture','host'=>'sip.example.invalid','port'=>5090,'transport'=>'tcp','username'=>'challengeuser','password'=>'challenge-password','register'=>false,'enabled'=>true,'auth_mode'=>'credentials','auth_username'=>'challengeauth','realm'=>'challenge-realm','from_user'=>'fromuser','from_domain'=>'from.example.invalid','register_proxy'=>'registrar.example.invalid:5091','outbound_proxy'=>'proxy.example.invalid:5092','expires'=>300,'limit'=>30,'codecs'=>['PCMA','G722'],'contact_user'=>'contactuser','extension_in_contact'=>true,'sip_cid_type'=>'pid','caller_id_in_from'=>false]],'ring_groups'=>[],'inbound_rules'=>[],'outbound_rules'=>[]];
 $newDomain=uuid();$s=$db->prepare('insert into v_domains(domain_uuid,domain_name,domain_enabled) values(?,?,true)');$s->execute([$newDomain,'advanced-fixture.example.invalid']);(new pbx_setup_provisioner($db))->apply($newDomain,'advanced-fixture.example.invalid',$generic);$r=$db->query("select * from v_gateways where gateway='Advanced setup fixture'")->fetch(PDO::FETCH_ASSOC);
 $check(!$r['register']&&!$r['enabled']&&$r['auth_username']==='challengeauth'&&$r['realm']==='challenge-realm'&&$r['codec_prefs']==='PCMA,G722'&&$r['outbound_proxy']==='proxy.example.invalid:5092'&&$r['extension_in_contact']==='true'&&$r['sip_cid_type']==='pid','Guided provisioning preserves complete advanced provider settings without enabling');
 $check($db->inTransaction(),'Reconciliation preserves caller transaction');$db->rollBack();$check((int)$db->query('select count(*) from v_pbx_restore')->fetchColumn()===0&&(int)$db->query('select count(*) from v_gateways')->fetchColumn()===0,'Caller rollback atomically removes restore and provider changes');
}finally {if($db->inTransaction())$db->rollBack();$db->exec('set search_path to public');$db->exec('drop schema if exists '.$schema.' cascade');}
echo 'PASS: '.$checks." synthetic V20 provider/auth/header/codec/DID and native transaction checks.\n";
