local P=loadfile('app/pbx_setup/resources/switch/scripts/app/pbx_setup/policy.lua')()
local n=0
local function check(value,why) n=n+1;assert(value,why) end
local function destination(number) return {type='Extension',number=number,external=''} end
local c={timezone='Africa/Johannesburg',departments={{number='GRP1',name='Sales',timezone='Africa/Johannesburg',members={{number='100',primary=true}},hours={type='SpecificHours',periods={{day=1,start='08:00', ['end']='17:00'}}},breaks={periods={{day=1,start='12:00',['end']='13:00'}}},holidays={{date='2026-12-25'}}}},users={['100']={profile='Available',auto_status='1',profiles={Available={available={NoAnswer={internal_inactive=false,internal=destination('101'),all=destination('102')}},away={}},Away={available={},away={Internal={outside_inactive=true,all=destination('103')},External={outside_inactive=false,all=destination('104'),outside=destination('105')}}},['Out of office']={available={},away={}}}}},outbound_rules={{prefix='0, +27',lengths='10-12',departments={'Sales'},ranges={},routes={{trunk_id='T1',strip=1,prepend='+27'}}},{prefix='9',lengths='',departments={},ranges={{from='200',to='299'}},routes={{trunk_id='T2',strip=1,prepend=''}}}}}
local clock=function(t) return function() return 1,t,'2026-10-05' end end
check(P.in_hours({type='AllHours'},0,'00:00'),'Always-open schedule')
check(P.in_hours(c.departments[1].hours,1,'08:00'),'Opening boundary')
check(not P.in_hours(c.departments[1].hours,1,'17:00'),'Closing boundary')
check(not P.in_hours(c.departments[1].hours,0,'12:00'),'Closed weekday')
check(P.office(c,'100',clock('09:00')),'Inside office hours')
check(not P.office(c,'100',clock('12:30')),'Break time')
check(not P.office(c,'100',clock('20:00')),'After hours')
check(not P.office(c,'100',function()return 1,'09:00','2026-12-25' end),'Holiday')
check(P.profile(c,'100',clock('09:00'))==c.users['100'].profiles.Available,'Automatic available status')
check(P.profile(c,'100',clock('12:30'))==c.users['100'].profiles.Away,'Automatic break status')
check(P.profile(c,'100',clock('20:00'))==c.users['100'].profiles['Out of office'],'Automatic closed status')
check(P.forward(c.users['100'].profiles.Available,'NoAnswer',true,true).number=='101','Internal unanswered destination')
check(P.forward(c.users['100'].profiles.Available,'NoAnswer',false,true).number=='102','External unanswered destination')
check(P.forward(c.users['100'].profiles.Away,'NoAnswer',false,false).number=='105','Outside-hours away destination')
check(P.forward(c.users['100'].profiles.Away,'NoAnswer',true,false).number=='103','Disabled outside-hours override')
check(P.outbound(c,'0111234567','100')==c.outbound_rules[1],'Matching department/prefix/length')
check(not P.outbound(c,'0111234567','300'),'Foreign department blocked')
check(not P.outbound(c,'011','100'),'Wrong length blocked')
check(P.outbound(c,'912345','200')==c.outbound_rules[2],'Extension range allowed')
check(not P.outbound(c,'912345','300'),'Extension range denied')
check(P.route_string('External..0123456789').external=='0123456789','External route string')
check(P.route_string('Extension.101.').number=='101','Internal route string')
check(P.route_string('ProceedWithNoExceptions..')==nil,'Continue route string')
print('PASS: '..n..' office-hours, forwarding and outbound decisions')
