server {
 listen 80; server_name @DOMAIN@;
 location ^~ /.well-known/acme-challenge/ { root /var/www/letsencrypt; }
 location / { return 301 https://$host$request_uri; }
}
server {
 listen 443 ssl; server_name @DOMAIN@;
 ssl_certificate "@CERT@"; ssl_certificate_key "@KEY@";
 root /var/www/fusionpbx; index index.php;
 client_max_body_size 2060M;
 add_header X-Content-Type-Options nosniff always;
 location ~ /\. { deny all; }
 location ~* \.(sql|lua|conf|key|zip)$ { deny all; }
 location ~ ^/(tests|packaging|platform)/ { deny all; }
 location / { try_files $uri $uri/ =404; }
 location ~ \.php$ {
  try_files $uri =404;
  include fastcgi_params;
  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  fastcgi_pass unix:/run/php/php8.4-fpm.sock;
  fastcgi_read_timeout 900s;
 }
}
