<?php
require_once dirname(__DIR__,2).'/resources/require.php';
require_once PROJECT_ROOT.'/resources/check_auth.php';
if (!permission_exists('pbx_service_view')) { http_response_code(403); exit('Access denied.'); }
header('Cache-Control: no-store');header('Referrer-Policy: no-referrer');
$portal=new pbx_tenants;$portal->guard();
$escape=fn($s)=>htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');
$view=$_GET['view']??'services';$error='';$edit=null;
if($_SERVER['REQUEST_METHOD']==='POST') {
    try {
        if(!(new token)->validate('/app/tenant_services/index.php')) { http_response_code(403);throw new RuntimeException('Your form expired. Refresh the page and try again.'); }
        switch($_POST['action']??'') {
            case 'invite': $_SESSION['pbx_invite_url']=pbx_paths::url().$portal->invite($_POST);$view='tenants';break;
            case 'renew_invite': $_SESSION['pbx_invite_url']=pbx_paths::url().$portal->renewInvitation($_POST['tenant_uuid']??'');$view='tenants';break;
            case 'suspend': $portal->suspend($_POST['tenant_uuid']??'',($_POST['enabled']??'')==='true');$view='tenants';break;
            case 'save_template': $portal->saveTemplate($_POST);$view='templates';$_SESSION['pbx_notice']='Template saved. Existing services keep their current setup.';break;
            case 'provision': $id=$portal->provision($_POST);$portal->switchService($id);header('Location: /core/desktop/');exit;
            case 'open': $portal->switchService($_POST['service_uuid']??'');header('Location: /core/desktop/');exit;
            default: throw new InvalidArgumentException('Choose an action.');
        }
        header('Location: ?view='.$view);exit;
    } catch(PDOException $e) { $error=$e->getCode()==='23505'?'This tenant, email, or service name is already in use.':'The change could not be saved. Please try again.';error_log('OpenWeb PBX tenant request failed: '.$e->getCode()); }
    catch(Throwable $e) { $error=$e->getMessage(); }
}
try { if($view==='editor'&&!empty($_GET['id']))$edit=$portal->template($_GET['id'],true); }catch(Throwable $e){http_response_code(403);$error='Template access denied.';$view='templates';}
$tenants=$portal->tenants();$templates=$portal->templates();$services=$portal->services();
$formToken=(new token)->create('/app/tenant_services/index.php');
$csrf=function()use($formToken,$escape){echo '<input type="hidden" name="'.$escape($formToken['name']).'" value="'.$escape($formToken['hash']).'">';};
$notice=$_SESSION['pbx_notice']??'';unset($_SESSION['pbx_notice']);
$invite=$_SESSION['pbx_invite_url']??'';unset($_SESSION['pbx_invite_url']);
$document['title']='Tenant Services';require_once PROJECT_ROOT.'/resources/header.php';
?>
<link rel="stylesheet" href="/app/tenant_services/workspace.css?v=1">
<script src="/app/tenant_services/workspace.js?v=1" defer></script>
<div class="tenant-workspace">
 <header class="portal-heading"><div><span class="portal-eyebrow">OPENWEB PBX</span><h1><?= $portal->platform()?'Tenant administration':'Your PBX workspace' ?></h1><p>Independent services. A setup that fits every team.</p></div><div class="portal-badge"><?= $portal->platform()?'Platform administrator':$escape($portal->tenant()['tenant_name']??'Tenant administrator') ?></div></header>
 <nav class="portal-tabs" aria-label="Tenant workspace"><a class="<?= $view==='services'?'selected':'' ?>" href="?view=services">PBX services</a><?php if(permission_exists('pbx_template_manage')): ?><a class="<?= in_array($view,['templates','editor'])?'selected':'' ?>" href="?view=templates">PBX templates</a><?php endif; ?><?php if($portal->platform()): ?><a class="<?= $view==='tenants'?'selected':'' ?>" href="?view=tenants">Tenants &amp; invitations</a><?php endif; ?></nav>
 <?php if($error): ?><div role="alert" class="portal-message error"><?= $escape($error) ?></div><?php endif; ?>
 <?php if($notice): ?><div role="status" class="portal-message"><?= $escape($notice) ?></div><?php endif; ?>
 <?php if($view==='tenants'&&$portal->platform()): ?>
  <?php if($invite): ?><div class="portal-message invite-message"><strong>Invitation ready — valid for 7 days</strong><p>Share this link with the tenant administrator. They choose their own password.</p><input aria-label="Tenant invitation link" readonly value="<?= $escape($invite) ?>"><button type="button" class="portal-button" data-copy-invite>Copy invitation</button></div><?php endif; ?>
  <section class="portal-card"><h2>Invite a tenant</h2><form method="post" class="portal-form"><?php $csrf(); ?><input type="hidden" name="action" value="invite"><div class="form-grid"><label>Tenant name<input name="tenant_name" required maxlength="120" placeholder="Acme Communications"></label><label>Tenant short name<input name="slug" required pattern="[a-z0-9][a-z0-9\-]{0,39}" maxlength="40" placeholder="acme"><small>Used in the tenant's SIP domains.</small></label><label>Administrator email<input type="email" name="email" required placeholder="admin@example.com"></label><label>Maximum PBX services<input type="number" name="service_limit" min="1" max="100" value="10" required></label></div><button class="portal-button primary" type="submit">Create invitation</button></form></section>
  <h2 class="section-heading">Tenants <span><?= count($tenants) ?></span></h2><div class="portal-grid"><?php foreach($tenants as $t): ?><article class="portal-card"><div class="card-top"><span class="tile-icon"><i class="fa-solid fa-building"></i></span><span class="state <?= $t['enabled']?'':'muted' ?>"><?= !$t['enabled']?'Suspended':($t['owner_user_uuid']?'Active':'Invited') ?></span></div><h3><?= $escape($t['tenant_name']) ?></h3><p><?= $escape($t['invite_email']) ?></p><p><?= (int)($t['service_count']??0) ?> / <?= (int)$t['service_limit'] ?> PBX services</p><form method="post"><?php $csrf(); ?><input type="hidden" name="action" value="suspend"><input type="hidden" name="tenant_uuid" value="<?= $escape($t['tenant_uuid']) ?>"><input type="hidden" name="enabled" value="<?= $t['enabled']?'false':'true' ?>"><button class="portal-button" type="submit"><?= $t['enabled']?'Suspend tenant':'Reactivate tenant' ?></button></form><?php if(!$t['owner_user_uuid']&&$t['enabled']): ?><form method="post"><?php $csrf(); ?><input type="hidden" name="action" value="renew_invite"><input type="hidden" name="tenant_uuid" value="<?= $escape($t['tenant_uuid']) ?>"><button class="portal-button" type="submit">Renew invitation</button></form><?php endif; ?></article><?php endforeach; ?></div>
 <?php elseif($view==='templates'&&permission_exists('pbx_template_manage')): ?>
  <div class="section-heading"><h2>Reusable PBX setups</h2><a class="portal-button primary" href="?view=editor">Create template</a></div><p class="section-description">Publish a template when it is ready. Every new service receives its own copy of the configuration.</p>
  <div class="portal-grid"><?php foreach($portal->templates(true) as $t): ?><article class="portal-card"><div class="card-top"><span class="tile-icon violet"><i class="fa-solid fa-layer-group"></i></span><span class="state <?= $t['published']?'':'muted' ?>"><?= $t['published']?'Published':'Draft' ?></span></div><h3><?= $escape($t['template_name']) ?></h3><p><?= $escape($t['description']) ?></p><p>Version <?= (int)$t['version'] ?> · <?= $t['tenant_uuid']?'Tenant template':'Shared template' ?></p><a class="portal-button" href="?view=editor&amp;id=<?= $escape($t['template_uuid']) ?>">Edit template</a></article><?php endforeach; ?></div>
 <?php elseif($view==='editor'&&permission_exists('pbx_template_manage')):
 $c=$edit['config']??['timezone'=>'Africa/Johannesburg','extension_start'=>100,'extension_count'=>2,'extension_limit'=>100,'trunks'=>[],'rules'=>[],'settings'=>[]];
 if(($_POST['action']??'')==='save_template'){$c=$_POST['config']??$c;$edit=array_merge($edit??[],$_POST);}
 ?>
  <form method="post" class="portal-form" id="template-form"><?php $csrf(); ?><input type="hidden" name="action" value="save_template"><input type="hidden" name="template_uuid" value="<?= $escape($edit['template_uuid']??'') ?>">
   <section class="portal-card"><h2><?= $edit?'Edit template':'Create a PBX template' ?></h2><div class="form-grid"><label>Template name<input name="template_name" required maxlength="120" value="<?= $escape($edit['template_name']??'') ?>" placeholder="Business PBX"></label><label class="check-label"><input type="checkbox" name="published" value="true" <?= !empty($edit['published'])?'checked':'' ?>>Publish for <?= $portal->platform()?'all tenants':'your tenant' ?></label><label class="full">Description<textarea name="description" maxlength="2000" rows="2" placeholder="Describe the setup and who should use it."><?= $escape($edit['description']??'') ?></textarea></label></div></section>
   <section class="portal-card"><h2>PBX defaults</h2><div class="form-grid three"><label>Timezone<select name="config[timezone]"><?php foreach(DateTimeZone::listIdentifiers() as $tz): ?><option value="<?= $escape($tz) ?>" <?= ($c['timezone']??'')===$tz?'selected':'' ?>><?= $escape($tz) ?></option><?php endforeach; ?></select></label><label>First extension<input type="number" name="config[extension_start]" min="100" max="999999999" required value="<?= (int)($c['extension_start']??100) ?>"></label><label>Extensions to create<input type="number" name="config[extension_count]" min="0" max="100" required value="<?= (int)($c['extension_count']??0) ?>"></label><label>Extension limit<input type="number" name="config[extension_limit]" min="1" max="10000" required value="<?= (int)($c['extension_limit']??100) ?>"></label><label>Outbound caller ID name<input name="config[caller_id_name]" maxlength="80" value="<?= $escape($c['caller_id_name']??'') ?>"></label><label>Outbound caller ID number<input name="config[caller_id_number]" maxlength="20" value="<?= $escape($c['caller_id_number']??'') ?>" placeholder="+27111234567"></label></div><p class="form-hint">Each extension gets a unique SIP password and a voicemail box.</p></section>
   <section class="portal-card"><div class="section-heading"><h2>SIP trunk presets</h2><button type="button" class="portal-button" data-add="trunks">Add trunk</button></div><p class="form-hint">Credentials can be stored in the template or supplied for each new service. Stored passwords are never shown here.</p><div id="trunks-rows" class="editor-rows"></div></section>
   <section class="portal-card"><div class="section-heading"><h2>Outbound calling rules</h2><button type="button" class="portal-button" data-add="rules">Add rule</button></div><p class="form-hint">Use an anchored number pattern and capture the number to send as $1, for example ^(0[0-9]{9})$. Rules apply inside the new PBX only.</p><div id="rules-rows" class="editor-rows"></div></section>
   <section class="portal-card"><div class="section-heading"><h2>Additional domain settings</h2><button type="button" class="portal-button" data-add="settings">Add setting</button></div><p class="form-hint">Preconfigure voicemail, recording, email, devices, SIP, and other domain business settings using their existing category and setting names.</p><div id="settings-rows" class="editor-rows"></div></section>
   <div class="form-actions"><a class="portal-button" href="?view=templates">Cancel</a><button class="portal-button primary" type="submit">Save template</button></div>
  </form>
  <?php foreach($c['trunks']??[] as &$g){$g['has_password']=!empty($g['password']);unset($g['password']);}unset($g);foreach($c['settings']??[] as &$s){if(preg_match('/password|secret|token/i',$s['subcategory']??'')){$s['has_secret']=!empty($s['value']);$s['value']='';}}unset($s); ?>
  <script type="application/json" id="template-editor-data"><?= json_encode($c,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script>
 <?php else: ?>
  <div class="section-heading"><h2>PBX services <span><?= count($services) ?></span></h2><?php if(permission_exists('pbx_service_create')): ?><a class="portal-button primary" href="#new-service">New PBX service</a><?php endif; ?></div>
  <?php if(!$services): ?><div class="portal-card empty-state"><span class="tile-icon"><i class="fa-solid fa-phone"></i></span><h3>Your next PBX starts here</h3><p><?= $portal->platform()?'Invite a tenant, then choose a template to build its first service.':'Choose a published template below to create your first PBX service.' ?></p></div><?php endif; ?>
  <div class="portal-grid"><?php foreach($services as $s): ?><article class="portal-card"><div class="card-top"><span class="tile-icon"><i class="fa-solid fa-phone"></i></span><span class="state <?= $s['enabled']?'':'muted' ?>"><?= $s['enabled']?'Provisioned':'Suspended' ?></span></div><h3><?= $escape($s['service_name']) ?></h3><p><?= $escape($s['tenant_name']) ?></p><p class="service-realm"><?= $escape($s['domain_name']) ?></p><p><?= $escape($s['template_name']) ?> · Version <?= (int)$s['template_version'] ?></p><form method="post"><?php $csrf(); ?><input type="hidden" name="action" value="open"><input type="hidden" name="service_uuid" value="<?= $escape($s['service_uuid']) ?>"><button type="submit" class="portal-button" <?= !$s['enabled']?'disabled':'' ?>>Open PBX desktop</button></form></article><?php endforeach; ?></div>
  <?php if(permission_exists('pbx_service_create')): ?><section class="portal-card" id="new-service"><h2>Create a PBX service</h2><form method="post" class="portal-form"><?php $csrf(); ?><input type="hidden" name="action" value="provision"><input type="hidden" name="request_uuid" value="<?= uuid() ?>"><div class="form-grid"><label>Tenant<select name="tenant_uuid" required><option value="">Choose a tenant</option><?php foreach($tenants as $t):if(!$t['owner_user_uuid']||!$t['enabled'])continue; ?><option value="<?= $escape($t['tenant_uuid']) ?>"><?= $escape($t['tenant_name']) ?></option><?php endforeach; ?></select></label><label>PBX template<select name="template_uuid" id="service-template" required><option value="">Choose a published template</option><?php foreach($templates as $t): ?><option value="<?= $escape($t['template_uuid']) ?>"><?= $escape($t['template_name']) ?> · v<?= (int)$t['version'] ?></option><?php endforeach; ?></select></label><label>Service name<input name="service_name" maxlength="120" required placeholder="Head office"></label><label>Service short name<input name="slug" required pattern="[a-z0-9][a-z0-9\-]{0,39}" maxlength="40" placeholder="head-office"></label></div><div id="service-preview" class="service-preview" aria-live="polite"></div><div id="service-credentials" class="form-grid"></div><p class="form-hint">Use call.openweb.co.za as the SIP server or outbound proxy, with the new service's SIP domain as the realm. Trunks requiring missing credentials stay disabled until configured.</p><button class="portal-button primary" type="submit" <?= !$templates?'disabled':'' ?>>Create PBX service</button></form></section><?php endif; ?>
  <?php $publicTemplates=[];foreach($templates as $t){$item=$portal->template($t['template_uuid']);$publicTemplates[$t['template_uuid']]=['name'=>$t['template_name'],'description'=>$t['description'],'extensions'=>$item['config']['extension_count'],'timezone'=>$item['config']['timezone'],'trunks'=>array_map(fn($g)=>['name'=>$g['name'],'has_username'=>!empty($g['username']),'has_password'=>!empty($g['password'])],$item['config']['trunks'])];} ?>
  <script type="application/json" id="service-template-data"><?= json_encode($publicTemplates,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script>
 <?php endif; ?>
</div>
<?php require_once PROJECT_ROOT.'/resources/footer.php'; ?>
