<?php if(!isset($admin,$view,$row)){http_response_code(404);exit;} ?>
<?php if($view==='users'): $profile=$row['profiles'][$row['profile']??'Available']??[]; ?>
<div class="admin-tabs" role="tablist"><?php foreach(['general'=>'General','forwarding'=>'Call Forwarding','voicemail'=>'Voicemail','provisioning'=>'Phone Provisioning','options'=>'Options'] as $tab=>$label): ?><button type="button" data-tab="<?= $tab ?>" class="<?= $tab==='general'?'selected':'' ?>" role="tab" aria-selected="<?= $tab==='general'?'true':'false' ?>"><?= $label ?></button><?php endforeach; ?></div>
<input type="hidden" name="editing_profile" value="<?= $e($row['profile']??'Available') ?>"><div data-panel="general"><div class="setup-fields"><?php $input('number','Extension',$row['number']??'','text',$key==='new'?'required pattern="[0-9]{2,10}"':'readonly');$input('name','Name',$row['name']??'','text','required maxlength="80"');$input('email','Email',$row['email']??'','email');$input('mobile','Mobile Number',$row['mobile']??'','tel');$select('department','Department',[''=>'None']+array_map($departmentName,array_column($c['departments'],'name','number')),$department($key)['number']);$statuses=array_keys($row['profiles']??array_fill_keys(['Available','Away','Out of office','Custom 1','Custom 2'],[]));$select('profile','Status',array_combine($statuses,$statuses),$row['profile']??'Available'); ?></div><?php $check('enabled','Enable This User',$row['enabled']??true); ?></div>
<div data-panel="forwarding"><div class="setup-fields"><?php $input('timeout','Ring Time (seconds)',$profile['timeout']??20,'number','min="1" max="600"');$check('ring_mobile','Ring My Mobile',$profile['ring_mobile']??false);$check('auto_status','Automatically Switch Status Outside Office Hours',((int)($row['auto_status']??0)%2)===1);if($key!=='new')foreach(['NoAnswer'=>'No Answer','Busy'=>'Busy','NotRegistered'=>'Not Registered'] as $reason=>$label)$dest(['NoAnswer'=>'no_answer','Busy'=>'busy','NotRegistered'=>'not_registered'][$reason],$label,$profile['available'][$reason]['all']??['type'=>'VoiceMail','number'=>$key==='new'?'':$key]);if(!empty($profile['away']))$dest('away','Forward Calls To',$profile['away']['External']['all']); ?></div></div>
<div data-panel="voicemail"><?php $check('voicemail_enabled','Enable Voicemail',$row['voicemail_enabled']??true); ?><div class="setup-fields"><?php $select('voicemail_email','Email Options',['None'=>'Do Not Send Email','Notification'=>'Email Notification','Attachment'=>'Attach Voicemail','AttachmentAndDelete'=>'Attach and Delete Voicemail'],$row['voicemail_email']??'None');if(!empty($row['greetings']))$select('greeting_id','Greeting',[''=>'Default Greeting']+array_column($row['greetings'],'title','id'),$row['greeting_id']??''); ?></div><p>Voicemail uses the email address on the General tab.</p><a class="setup-button" href="?view=voicemails">Voicemail</a></div>
<div data-panel="provisioning"><p>Server: <strong><?= $e(pbx_paths::host()) ?></strong></p><?php if($key!=='new'): ?><button class="setup-button" type="submit" name="action" value="credentials">Show Phone Details</button><?php else: ?><p>Save this user to get phone details.</p><?php endif; ?></div>
<div data-panel="options"><div class="setup-fields"><?php $input('outbound_caller_id','Outbound Caller ID',$row['outbound_caller_id']??'','tel');$check('record_calls','Record Calls',$row['record_calls']??false); ?></div></div>
<?php elseif($view==='voice'):
$gateway=$key==='new'?[]:($database->select("select username,auth_username,realm,from_user,from_domain,register_proxy,outbound_proxy,register_transport,expire_seconds,channels,codec_prefs,extension,extension_in_contact,caller_id_in_from,sip_cid_type,coalesce(password,'')<>'' has_password from v_gateways where domain_uuid=:d and gateway_uuid=:id",['d'=>$_SESSION['domain_uuid'],'id'=>$row['gateway_uuid']],'row')?:[]);
$authentication=($row['auth_mode']??((!empty($row['register'])||!empty($gateway['username']))?'credentials':'ip'))==='credentials'?'password':'ip';
$advanced=static fn($field,$native=null)=>$row[$field]??$gateway[$native??$field]??'';
if($key!=='new'&&isset($readiness['trunks'][$key])):$state=$readiness['trunks'][$key]; ?>
<div class="trunk-readiness"><h3><?= $trunkStatus($state) ?></h3><p><?= $e($state['next_step']) ?></p><?php if($state['issues']): ?><ul><?php foreach($state['issues'] as $issue): ?><li><?= $e($issue) ?></li><?php endforeach; ?></ul><?php endif; ?><p><?= (int)$state['incoming_off'] ?> of <?= (int)$state['incoming_total'] ?> incoming numbers are off. <?= (int)$state['outbound_routes'] ?> outgoing routes use this trunk.</p>
<?php if(permission_exists('gateway_edit')): ?><button class="setup-button" type="submit" name="action" value="check_provider" formnovalidate data-provider-check>Check saved provider</button><p class="setup-hint">Checks the saved server address and TCP/TLS connection. It sends no registration, SIP message or call and does not apply unsaved changes.</p><?php endif; ?></div>
<?php endif; ?>
<div class="setup-fields"><?php
$input('name','Name',$row['name']??'','text','required');$input('host','Registrar/Server',$row['host']??'','text','required');
$input('port','Port',$row['port']??5060,'number','min="1" max="65535"');$select('transport','Transport',['udp'=>'UDP','tcp'=>'TCP','tls'=>'TLS'],$row['transport']??$gateway['register_transport']??'udp');
$input('main_number','Main Trunk Number',$row['main_number']??'','tel');$select('authentication','Authentication',['ip'=>'IP Authentication','password'=>'Username and Password'],$authentication,'data-authentication');
echo '<div data-password-auth>';$input('username','Account ID',$gateway['username']??'');echo '</div><div data-password-auth>';$input('password','Authentication Password','','password','autocomplete="new-password" placeholder="Leave blank to keep the saved password"');echo '<small>'.(!empty($gateway['has_password'])?'A password is saved.':'No password is saved.').'</small></div>';
$input('caller_id','Outbound Caller ID',$row['caller_id']??'','tel');$input('allowed_ips','Provider IP Addresses',implode(', ',$row['allowed_ips']??[])); ?></div>
<input type="hidden" name="register" value="0"><?php $check('register','Register with provider',$row['register']??false); ?>
<?php $check('enabled','Enable SIP Trunk',$row['enabled']??false); ?>
<p>For IP Authentication, ask your provider to whitelist <strong><?= $e(pbx_paths::address()) ?></strong>. The incoming SIP address for UDP/TCP is <strong><?= $e($admin->providerAddress()) ?></strong>.</p>
<details class="trunk-advanced"><summary>Advanced provider settings</summary><p>Keep the settings supplied by your provider. Registration and password authentication are separate options.</p>
<div class="setup-fields"><?php
$select('source_field','Incoming number is supplied in',['ToUserPart'=>'To: User Part','RequestLineURIUser'=>'Request Line URI: User Part'],$row['source_field']??'ToUserPart');
$input('realm','Authentication Realm',$advanced('realm'));$input('auth_username','Authentication ID (optional override)',$advanced('auth_username'));
$input('from_user','From: User Part',$advanced('from_user'));$input('from_domain','From: Host Part',$advanced('from_domain'));
$input('register_proxy','Registration Server (optional)',$advanced('register_proxy'));$input('outbound_proxy','Outbound Proxy (optional)',$advanced('outbound_proxy'));
$input('expires','Registration Refresh (seconds)',$row['expires']??$gateway['expire_seconds']??180,'number','min="1" max="86400"');
$input('limit','Maximum Simultaneous Calls',$row['limit']??$gateway['channels']??10,'number','min="1" max="10000"');
$input('codecs','Codecs',implode(', ',$row['codecs']??array_filter(explode(',',(string)($gateway['codec_prefs']??'')))));
$input('contact_user','Contact: User Part',$advanced('contact_user','extension'));
$cid=$row['sip_cid_type']??($gateway['sip_cid_type']??'');if($cid==='')$cid=isset($row['headers']['RemotePartyIDCallingPartyUserPart'])?'rpid':(isset($row['headers']['PAssertedIdentityUserPart'])?'pid':'none');
$select('sip_cid_type','Caller ID Header',['none'=>'None','rpid'=>'Remote Party ID','pid'=>'P-Asserted-Identity'],$cid);
?></div>
<input type="hidden" name="extension_in_contact" value="0"><?php $check('extension_in_contact','Use Contact: User Part',filter_var($advanced('extension_in_contact'),FILTER_VALIDATE_BOOLEAN)); ?>
<input type="hidden" name="caller_id_in_from" value="0"><?php $check('caller_id_in_from','Use outgoing caller ID in From',filter_var($advanced('caller_id_in_from'),FILTER_VALIDATE_BOOLEAN)); ?>
</details>
<?php elseif($view==='departments'): ?><div class="setup-fields"><?php $input('name','Name',$row['name']??'','text','required'); ?></div><h3>Users</h3><?php $members($row['members']??[]); ?>
<?php elseif($view==='hours'): $periods=[];foreach($row['hours']['periods']??[] as $p)$periods[$p['day']]=$p; ?>
<h3><?= $e($departmentName($row['name'])) ?></h3><div class="setup-fields"><?php $select('timezone','Timezone',array_combine(DateTimeZone::listIdentifiers(),DateTimeZone::listIdentifiers()),$row['timezone']);$check('always_open','Always Open',($row['hours']['type']??'')==='AllHours'); ?></div>
<div class="setup-table-wrap"><table class="setup-table admin-hours"><thead><tr><th>Day</th><th>Open</th><th>From</th><th>To</th></tr></thead><tbody><?php foreach([1=>'Monday',2=>'Tuesday',3=>'Wednesday',4=>'Thursday',5=>'Friday',6=>'Saturday',0=>'Sunday'] as $day=>$label): ?><tr><td><?= $label ?></td><td><?php $check('days['.$day.'][open]','Open',isset($periods[$day])); ?></td><td><?php $input('days['.$day.'][start]','From',$periods[$day]['start']??'08:00','time'); ?></td><td><?php $input('days['.$day.'][end]','To',$periods[$day]['end']??'17:00',($periods[$day]['end']??'')==='24:00'?'text':'time'); ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php elseif(in_array($view,['queues','ring_groups','receptionists'],true)): ?>
<div class="setup-fields"><?php $input('name','Name',$row['name']??'','text','required');$input('number','Extension',$row['number']??'','text',$key==='new'?'required pattern="[0-9]{2,10}"':'readonly');$input('timeout',$view==='queues'?'Maximum Queue Wait Time (seconds)':($view==='receptionists'?'Timeout (seconds)':'Ring Time (seconds)'),$row['timeout']??30,'number','min="1" max="86400"');if($view==='queues'){$input('ring_timeout','Agent Ring Time (seconds)',$row['ring_timeout']??30,'number','min="1" max="600"');$input('wrap_up','Wrap-up Time (seconds)',$row['wrap_up']??2,'number','min="0" max="600"');$select('intro','Intro Prompt',$audioChoices,$audioIds[$row['intro']??'']??'');$select('moh','Music on Hold',$audioChoices,$audioIds[$row['moh']??'']??'');$select('callback_mode','Queue Callbacks',['disabled'=>'Disabled','request'=>'Triggered on User Request (press 2)','offer'=>'Offer a Callback After a Wait','automatic'=>'Triggered Automatically'],$row['callback_mode']??'disabled');$input('callback_after','Callback Wait (seconds)',$row['callback_after']??600,'number','min="1" max="86400"');$input('callback_attempts','Maximum Attempts',$row['callback_attempts']??3,'number','min="1" max="5"');$input('callback_prefix','Callback Outbound Prefix',$row['callback_prefix']??'');}if($view==='receptionists')$select('prompt','Prompt',$audioChoices,$audioIds[$row['prompt']??'']??'');$dest('destination','Destination if No Answer',$row['destination']??$row['timeout_destination']??[]); ?></div>
<?php if($view!=='receptionists'): ?><h3><?= $view==='queues'?'Agents':'Users' ?></h3><?php $members($row['members']??[]); ?><p>Ringing Strategy: <strong>Ring All</strong></p>
<?php else: ?><h3>Menu Options</h3><div class="setup-fields"><?php $optionsByKey=[];foreach($row['options']??[] as $o)$optionsByKey[$o['digit']]=$o['destination'];foreach(['0','1','2','3','4','5','6','7','8','9','*','#'] as $digit){$select('options['.$digit.'][destination]','Key '.$digit,[''=>'No Action']+$admin->destinations($c),isset($optionsByKey[$digit])?$optionsByKey[$digit]['type'].':'.$optionsByKey[$digit]['number']:'','data-destination');echo '<div data-external>';$input('options['.$digit.'][destination_external]','External Number',$optionsByKey[$digit]['external']??'','tel');echo '</div>';} ?></div><?php endif; ?>
<?php elseif($view==='outbound'): ?><div class="setup-fields"><?php $input('name','Name',$row['name']??'','text','required');$input('prefix','Calls to Numbers Starting with Prefix',$row['prefix']??'');$input('lengths','Calls to Numbers with a Length of',$row['lengths']??''); ?></div><p>Separate multiple prefixes or lengths with commas.</p><h3>Make Outbound Calls On</h3><div class="admin-routes"><?php $trunkChoices=[''=>'No Route'];foreach($c['trunks'] as $n=>$t)$trunkChoices[$n]=$t['name'];for($i=0;$i<5;$i++):$r=$row['routes'][$i]??[]; ?><div class="setup-fields"><?php $select('routes['.$i.'][trunk_id]','Route '.($i+1),$trunkChoices,$r['trunk_id']??'');$input('routes['.$i.'][strip]','Strip Digits',$r['strip']??0,'number','min="0" max="20"');$input('routes['.$i.'][prepend]','Prepend',$r['prepend']??'');$input('routes['.$i.'][caller_id]','Outbound Caller ID',$r['caller_id']??'','tel'); ?></div><?php endfor; ?></div><?php if(!empty($row['departments'])||!empty($row['ranges'])): ?><p>This rule’s user and department restrictions are retained.</p><?php endif; ?>
<?php elseif($view==='incoming'): ?><?php if($key==='new'): ?><div class="setup-fields"><?php $input('number','DID Number','','tel','required');$select('trunk_id','SIP Trunk',array_column($c['trunks'],'name','number')); ?></div><?php else: ?><p><?= $e($row['name']) ?> · <?= $e($row['number']?:'All Calls') ?></p><?php endif; ?><div class="setup-fields"><?php $dest('office','When Office Is Open',$row['office']??[]);$dest('outside','When Office Is Closed',$row['outside']??[]); ?></div><?php $check('use_outside','Use Office Hours',$row['use_outside']??false);$check('enabled','Enable Incoming Calls',$row['enabled']??false); ?>
<?php elseif($view==='scripts'): ?><h3>PIN Menu</h3><p>PINs stay private. Choose the user for each existing PIN.</p><div class="setup-fields"><?php $choices=[];foreach($c['users'] as $n=>$u)$choices[$n]=$n.' · '.$u['name'];$i=0;foreach($row['pin_map']??[] as $pin=>$target){$list=$choices;if(!isset($list[$target]))$list=[$target=>'Missing User — choose a replacement']+$list;$select('pin_routes['.$i.'][number]','PIN '.($i+1),$list,$target);$i++;} ?></div>
<?php endif; ?>
