<?php if(empty($openweb_guided)){http_response_code(404);exit;} ?>
<?php
/** OpenWeb PBX guided administration. Native applications retain their authorization checks. */
require_once dirname(__DIR__, 2).'/resources/require.php';
require_once PROJECT_ROOT.'/resources/check_auth.php';
$setup = new pbx_setup;
if (!$setup->canManage()) { http_response_code(403); exit('Access denied.'); }
header('Cache-Control: no-store');
header('Referrer-Policy: no-referrer');
$escape = static fn($value) => htmlspecialchars(is_scalar($value) || $value === null ? (string)$value : '', ENT_QUOTES, 'UTF-8');
$view = (string)($_GET['view'] ?? 'overview');
$error = '';
$draft = null;
$draftId = (string)($_GET['draft'] ?? '');
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    try {
        if (!(new token)->validate('/app/pbx_setup/index.php')) {
            http_response_code(403);
            throw new RuntimeException('Your form expired. Refresh the page and try again.');
        }
        switch ($_POST['action'] ?? '') {
            case 'review_setup':
                $draft = $setup->reviewSetup($_POST);
                header('Location: /app/pbx_setup/?view=review&draft='.rawurlencode($draft['draft_id'])); exit;
            case 'create_setup':
                if (empty($_POST['acknowledged'])) throw new InvalidArgumentException('Confirm the setup before creating your PBX.');
                $domain = $setup->createSetup((string)($_POST['draft_id'] ?? ''));
                $setup->switchDomain($domain);
                $_SESSION['pbx_setup_notice'] = 'Your PBX is ready. Connect your phones, then test incoming and outgoing calls.';
                header('Location: /app/pbx_setup/'); exit;
            case 'analyze_import':
                $draft = $setup->analyzeUpload($_FILES['backup'] ?? []);
                header('Location: /app/pbx_setup/?view=import_preview&draft='.rawurlencode($draft['draft_id'])); exit;
            case 'create_import':
                if (empty($_POST['acknowledge_limitations'])) throw new InvalidArgumentException('Review and acknowledge the migration report first.');
                $domain = $setup->createImport((string)($_POST['draft_id'] ?? ''), $_POST);
                $setup->switchDomain($domain);
                $_SESSION['pbx_setup_notice'] = 'The reviewed configuration was imported into a new PBX. Check the migration report and test every call flow before switching your live phones and numbers.';
                header('Location: /app/pbx_setup/'); exit;
            default: throw new InvalidArgumentException('Choose a setup action.');
        }
    } catch (PDOException $exception) {
        error_log('OpenWeb PBX guided setup failed: '.$exception->getCode());
        $error = $exception->getCode() === '23505' ? 'A PBX or user already uses these details. Choose a different service name or user number.' : 'The PBX change could not be saved. Please try again.';
    } catch (Throwable $exception) { $error = $exception->getMessage(); }
    $view = match ($_POST['action'] ?? '') {
        'review_setup' => 'wizard', 'create_setup' => 'review', 'analyze_import' => 'import', 'create_import' => 'import_preview', default => $view
    };
    $draftId = (string)($_POST['draft_id'] ?? $draftId);
}
$views = ['overview','users','voice','handling','settings','wizard','review','import','import_preview'];
if (!in_array($view, $views, true)) $view = 'overview';
$options = $setup->options();
$overview = $setup->overview();
if (in_array($view, ['review','import_preview'], true)) {
    try { $draft = $view === 'review' ? $setup->draft($draftId) : $setup->importPreview($draftId); }
    catch (Throwable $exception) { $error = $exception->getMessage(); $view = $view === 'review' ? 'wizard' : 'import'; }
}
$counts = $overview['counts'] ?? [];
$notice = (string)($_SESSION['pbx_setup_notice'] ?? ''); unset($_SESSION['pbx_setup_notice']);
$formToken = (new token)->create('/app/pbx_setup/index.php');
$csrf = static function() use ($formToken, $escape) { echo '<input type="hidden" name="'.$escape($formToken['name']).'" value="'.$escape($formToken['hash']).'">'; };
$values = $error && ($_POST['action'] ?? '') === 'review_setup' ? $_POST : [];
$timezone = (string)($values['timezone'] ?? $options['default_timezone'] ?? 'Africa/Johannesburg');
$tenant = (string)($values['tenant_uuid'] ?? $options['current_tenant_uuid'] ?? '');
$company = (string)($values['company_name'] ?? $options['default_company_name'] ?? '');
$sourceIp = filter_var($_SERVER['SERVER_ADDR'] ?? '', FILTER_VALIDATE_IP) ?: '';
$serviceName = (string)($values['service_name'] ?? 'Main office');
$renderTenant = static function(string $selected = '') use ($options, $escape) {
    $tenants = $options['tenants'] ?? [];
    if (permission_exists('pbx_tenant_manage')) {
        echo '<label>Company workspace<select name="tenant_uuid"><option value="">My company</option>';
        foreach ($tenants as $item) echo '<option value="'.$escape($item['tenant_uuid']).'" '.($selected === $item['tenant_uuid'] ? 'selected' : '').'>'.$escape($item['tenant_name']).'</option>';
        echo '</select><small>Each company gets its own PBX settings, users, and call rules.</small></label>';
    } else echo '<input type="hidden" name="tenant_uuid" value="'.$escape($selected).'">';
};
$renderTimezone = static function(string $selected) use ($options, $escape) {
    echo '<label>Timezone<select name="timezone" required>';
    foreach ($options['timezones'] ?? DateTimeZone::listIdentifiers() as $value) echo '<option value="'.$escape($value).'" '.($selected === $value ? 'selected' : '').'>'.$escape(str_replace('_', ' ', $value)).'</option>';
    echo '</select><small>Used for office hours and voicemail timestamps.</small></label>';
};
$renderUser = static function(string|int $index, array $user = [], bool $first = false) use ($escape) {
    echo '<div class="setup-user-row" data-user-row><label>Extension<input name="users['.$escape($index).'][number]" data-user-number inputmode="numeric" pattern="[0-9]{2,9}" maxlength="9" value="'.$escape($user['number'] ?? ($first ? '100' : '')).'" '.($first ? 'required' : '').' placeholder="101"></label><label>Name<input name="users['.$escape($index).'][name]" data-user-name maxlength="80" value="'.$escape($user['name'] ?? '').'" '.($first ? 'required' : '').' placeholder="Alex Morgan"></label><label>Email <small>Optional</small><input type="email" name="users['.$escape($index).'][email]" maxlength="254" value="'.$escape($user['email'] ?? '').'" placeholder="alex@example.com"></label><button type="button" class="setup-button danger" data-remove-user aria-label="Remove this user" '.($first ? 'hidden' : '').'><i class="fa-solid fa-xmark" aria-hidden="true"></i></button></div>';
};
$link = static function(string $permission, string $url, string $icon, string $title, string $description) use ($escape) {
    if (!permission_exists($permission)) return;
    echo '<a class="setup-link" href="'.$escape($url).'"><i class="fa-solid '.$escape($icon).'" aria-hidden="true"></i><div><strong>'.$escape($title).'</strong><span>'.$escape($description).'</span></div><i class="fa-solid fa-chevron-right" aria-hidden="true"></i></a>';
};
$document['title'] = 'Admin';
require_once PROJECT_ROOT.'/resources/header.php';
?>
<link rel="stylesheet" href="/app/pbx_setup/setup.css?v=2">
<script src="/app/pbx_setup/setup.js?v=1" defer></script>
<main class="pbx-setup">
    <header class="setup-heading"><div><span class="setup-eyebrow">OPENWEB PBX · ADMIN CONSOLE</span><h1>Admin</h1><p>Manage your phone system.</p></div><span class="setup-domain"><?= $escape($overview['company_name'] ?? $overview['domain_name'] ?? 'Your company') ?></span></header>
    <div class="setup-shell">
        <nav class="setup-nav" aria-label="PBX administration">
            <?php foreach (['overview'=>['fa-house','Overview'],'users'=>['fa-users','Users'],'voice'=>['fa-phone-volume','Voice & Chat'],'handling'=>['fa-diagram-project','Call handling'],'settings'=>['fa-sliders','Settings']] as $key=>$item): ?><a href="?view=<?= $key ?>" class="<?= $view === $key ? 'selected' : '' ?>" <?= $view === $key ? 'aria-current="page"' : '' ?>><i class="fa-solid <?= $item[0] ?>" aria-hidden="true"></i><?= $item[1] ?></a><?php endforeach; ?>
            <span class="setup-nav-label">GET STARTED</span>
            <a href="?view=wizard" class="<?= in_array($view,['wizard','review'],true) ? 'selected' : '' ?>"><i class="fa-solid fa-wand-magic-sparkles" aria-hidden="true"></i>New PBX</a>
            <a href="?view=import" class="<?= in_array($view,['import','import_preview'],true) ? 'selected' : '' ?>"><i class="fa-solid fa-file-import" aria-hidden="true"></i>Import 3CX backup</a>
        </nav>
        <div class="setup-content">
            <?php if ($notice): ?><div class="setup-message" role="status"><?= $escape($notice) ?></div><?php endif; ?>
            <?php if ($error): ?><div class="setup-message error" role="alert"><?= $escape($error) ?><?php if ($view === 'wizard' && !empty($values['trunk']['password'])): ?><p>Enter the trunk password again before continuing.</p><?php endif; ?></div><?php endif; ?>
            <?php if ($view === 'wizard'):
                $userRows = is_array($values['users'] ?? null) ? array_values(array_filter($values['users'], 'is_array')) : [['number'=>'100','name'=>'','email'=>'']];
                if (!$userRows) $userRows = [['number'=>'100','name'=>'','email'=>'']];
                $trunk = is_array($values['trunk'] ?? null) ? $values['trunk'] : [];
                $outbound = is_array($values['outbound'] ?? null) ? $values['outbound'] : [];
                $authentication = in_array($trunk['authentication'] ?? '', ['ip','password'], true) ? $trunk['authentication'] : 'ip';
            ?>
                <ol class="setup-steps" aria-label="Setup progress"><li class="active" data-step-indicator><span>1</span>Company</li><li data-step-indicator><span>2</span>People</li><li data-step-indicator><span>3</span>Phone service</li><li data-step-indicator><span>4</span>Call handling</li><li><span>5</span>Review</li></ol>
                <form method="post" class="setup-form setup-card" data-setup-wizard autocomplete="off">
                    <?php $csrf(); ?><input type="hidden" name="action" value="review_setup">
                    <span class="sr-only" role="status" data-step-announcement></span>
                    <section data-setup-step data-title="Your company"><h2 tabindex="-1">Let's start with your company.</h2><p>A few details are all you need. Your PBX will have its own users, numbers, and call rules.</p><div class="setup-fields"><label>Company name<input name="company_name" required maxlength="120" value="<?= $escape($company) ?>" placeholder="Acme Communications"></label><label>PBX name<input name="service_name" required maxlength="120" value="<?= $escape($serviceName) ?>" placeholder="Main office"><small>Choose a name your team will recognize.</small></label><?php $renderTenant($tenant); $renderTimezone($timezone); ?></div></section>
                    <section data-setup-step data-title="Users and phones"><h2 tabindex="-1">Who needs a phone?</h2><p>Add a name and extension for each person. SIP passwords and voicemail boxes are created automatically.</p><div data-user-rows><?php foreach ($userRows as $i=>$user) $renderUser($i,$user,$i===0); ?><details data-extra-users><summary class="setup-row-title">Additional users</summary><?php for($i=count($userRows);$i<count($userRows)+4;$i++)$renderUser($i); ?></details></div><div class="setup-actions"><button type="button" class="setup-button" data-add-user hidden><i class="fa-solid fa-plus" aria-hidden="true"></i>Add user</button></div><p class="setup-hint">An email address is optional. It is used for voicemail delivery when outgoing mail is configured.</p></section>
                    <section data-setup-step data-title="Phone service"><h2 tabindex="-1">Connect your phone provider.</h2><p>Enter your provider's SIP trunk details. You can leave the server blank and add a provider later.</p><div class="setup-fields"><label>Provider / trunk name<input name="trunk[name]" maxlength="60" value="<?= $escape($trunk['name'] ?? 'Phone provider') ?>" placeholder="Phone provider"></label><label>SIP server<input name="trunk[host]" maxlength="253" value="<?= $escape($trunk['host'] ?? '') ?>" placeholder="sip.provider.com"><small>Use the server address supplied by your provider.</small></label><label>Port<input type="number" name="trunk[port]" min="1" max="65535" value="<?= $escape($trunk['port'] ?? '5060') ?>"></label><label>Transport<select name="trunk[transport]"><?php foreach(['udp'=>'UDP','tcp'=>'TCP','tls'=>'TLS'] as $key=>$label): ?><option value="<?= $key ?>" <?= ($trunk['transport'] ?? 'udp') === $key ? 'selected' : '' ?>><?= $label ?></option><?php endforeach; ?></select></label><label class="full">Authentication<select name="trunk[authentication]"><option value="ip" <?= $authentication === 'ip' ? 'selected' : '' ?>>IP Authentication — no username or password</option><option value="password" <?= $authentication === 'password' ? 'selected' : '' ?>>Username &amp; password</option></select></label></div><p class="setup-hint" data-ip-hint>Your provider must allow calls from this server<?= $sourceIp ? ' ('.$escape($sourceIp).')' : '' ?>. </p><div class="setup-fields" data-trunk-credentials><label>Username <small>Password authentication only</small><input name="trunk[username]" maxlength="200" value="<?= $escape($trunk['username'] ?? '') ?>" autocomplete="off"></label><label>Password <small>Password authentication only</small><input type="password" name="trunk[password]" maxlength="256" value="" autocomplete="new-password"><small>Your password is stored securely and is never shown in the review.</small></label></div></section>
                    <section data-setup-step data-title="Call handling"><h2 tabindex="-1">Decide where calls go.</h2><p>Start with one main number and a simple outbound rule. You can add groups, menus, and office hours after setup.</p><div class="setup-fields"><label>Main incoming number <small>Optional</small><input name="inbound_number" maxlength="20" inputmode="tel" pattern="[+0-9]{0,20}" value="<?= $escape($values['inbound_number'] ?? '') ?>" placeholder="+27111234567"><small>Use the exact number format delivered by your provider.</small></label><label>Who answers?<select name="inbound_destination"><option value="">Choose who answers</option><?php foreach($userRows as $user): if(empty($user['number']))continue; ?><option value="<?= $escape($user['number']) ?>" <?= ($values['inbound_destination'] ?? '') === (string)$user['number'] ? 'selected' : '' ?>><?= $escape($user['number'].' · '.($user['name'] ?? '')) ?></option><?php endforeach; ?></select><small>Calls go to this user's extension.</small></label></div><h3>Outgoing calls</h3><p class="setup-hint">Enter a calling prefix approved by your provider to create an outgoing rule. Leave the prefix blank to configure outgoing calls later.</p><div class="setup-fields three"><label>Dialing prefix <small>Optional</small><input name="outbound[prefix]" inputmode="tel" maxlength="10" pattern="[+0-9]{0,10}" value="<?= $escape($outbound['prefix'] ?? '') ?>" placeholder="For example, 0"><small>Numbers starting with this prefix use the trunk. Blank creates no outgoing rule.</small></label><label>Remove first digits<input type="number" name="outbound[strip]" min="0" max="10" value="<?= $escape($outbound['strip'] ?? '0') ?>"><small>For example, remove an outside-line access digit.</small></label><label>Add before number <small>Optional</small><input name="outbound[prepend]" inputmode="tel" maxlength="10" pattern="[+0-9]{0,10}" value="<?= $escape($outbound['prepend'] ?? '') ?>" placeholder="For example, +27"><small>Added to the number sent to your provider.</small></label></div><div class="setup-safety"><i class="fa-solid fa-shield-halved" aria-hidden="true"></i><span>The next page shows your complete setup for review. Nothing is created until you confirm it.</span></div></section>
                    <div class="setup-wizard-footer"><p>About five minutes to a configured PBX.</p><div><button type="button" class="setup-button" data-previous hidden>Back</button><button type="button" class="setup-button primary" data-next hidden>Continue<i class="fa-solid fa-arrow-right" aria-hidden="true"></i></button><button type="submit" class="setup-button primary" data-review>Review setup<i class="fa-solid fa-arrow-right" aria-hidden="true"></i></button></div></div>
                </form>
                <template id="setup-user-template"><?php $renderUser('__ROW__'); ?></template>
            <?php elseif ($view === 'review' && $draft): $summary=$draft['summary'] ?? []; ?>
                <ol class="setup-steps" aria-label="Setup progress"><li class="complete"><span>1</span>Company</li><li class="complete"><span>2</span>People</li><li class="complete"><span>3</span>Phone service</li><li class="complete"><span>4</span>Call handling</li><li class="active" aria-current="step"><span>5</span>Review</li></ol>
                <section class="setup-card"><h2>Everything ready for <?= $escape($summary['company_name'] ?? 'your company') ?>.</h2><p>Review your setup, then create an independent PBX. Existing PBXs keep their current configuration.</p><dl class="setup-review"><?php foreach(['company_name'=>'Company','service_name'=>'PBX name','timezone'=>'Timezone','user_count'=>'Users & voicemail boxes','trunk_count'=>'SIP trunks','number_count'=>'Incoming numbers','ring_group_count'=>'Ring groups'] as $key=>$label): ?><div><dt><?= $label ?></dt><dd><?= $escape($summary[$key] ?? ($key === 'ring_group_count' ? '0' : '—')) ?></dd></div><?php endforeach; ?></dl><?php if(!empty($draft['warnings'])): ?><div class="setup-message warning"><strong>Before you go live</strong><ul><?php foreach($draft['warnings'] as $warning): ?><li><?= $escape($warning) ?></li><?php endforeach; ?></ul></div><?php endif; ?><form method="post" class="setup-form"><?php $csrf(); ?><input type="hidden" name="action" value="create_setup"><input type="hidden" name="draft_id" value="<?= $escape($draftId) ?>"><label class="setup-check-label"><input type="checkbox" name="acknowledged" value="1" required><span>I have reviewed this setup and want to create this PBX.</span></label><div class="setup-actions"><a class="setup-button" href="?view=wizard">Start again</a><button type="submit" class="setup-button primary">Create my PBX<i class="fa-solid fa-check" aria-hidden="true"></i></button></div></form></section>
            <?php elseif ($view === 'import'): ?>
                <div class="setup-message warning"><strong>Restore a 3CX backup.</strong><p>3CX V20 Update 9 backups are supported. Review the backup before creating a PBX.</p></div>
                <section class="setup-card"><div class="setup-card-top"><span class="setup-icon violet"><i class="fa-solid fa-file-import" aria-hidden="true"></i></span><span class="setup-state">Review before import</span></div><h2>Backup & Restore</h2><p>Choose your 3CX backup. We will show what will be restored and anything that needs attention before creating your PBX.</p><form method="post" enctype="multipart/form-data" class="setup-form"><?php $csrf(); ?><input type="hidden" name="action" value="analyze_import"><div class="setup-dropzone"><i class="fa-solid fa-cloud-arrow-up" aria-hidden="true"></i><label>Choose a 3CX backup<input type="file" name="backup" accept=".zip,.xml" required><small>ZIP up to 2 GB, or XML up to 8 MB. Encrypted backups must be exported without encryption first.</small></label></div><button type="submit" class="setup-button primary">Check backup<i class="fa-solid fa-arrow-right" aria-hidden="true"></i></button></form><div class="setup-safety"><i class="fa-solid fa-shield-halved" aria-hidden="true"></i><span>Passwords are never displayed in the preview. Your current PBX configuration stays in place while the backup is reviewed.</span></div></section>
                <div class="setup-message warning"><strong>Your restore report.</strong><p>Users, call handling, office hours, recordings, voicemail and phone details can be restored from the checked V20 backup. The report lists anything needing attention. 3CX apps and its hosted email service need new connections.</p></div>
            <?php elseif ($view === 'import_preview' && $draft):
                $summary=$draft['summary'] ?? []; $importCounts=$draft['counts'] ?? []; $supported=!empty($draft['supported']);
                $sourceVersion=(string)($summary['source_version'] ?? $draft['source_version'] ?? 'unknown');
                $sourceFormat=(string)($summary['source_format'] ?? $draft['source_format'] ?? '');
                $sourceTitle=$sourceVersion==='documented setup schema'?'Documented 3CX setup XML':($sourceVersion==='unknown'?'3CX configuration':'3CX '.$sourceVersion);
                $sourceFormatLabel=['3cx-v20-backup'=>'V20 backup','3cx-native-xml'=>'Native XML backup','3cx-native-zip'=>'Native ZIP backup','3cx-setupconfig-xml'=>'Setup configuration','3cx-setupconfig-zip'=>'Setup configuration archive'][$sourceFormat] ?? 'Configuration';
                $importCompany=(string)($_POST['company_name'] ?? $summary['company_name'] ?? $company);
                $importService=(string)($_POST['service_name'] ?? $summary['service_name'] ?? 'Imported PBX');
                $importTimezone=(string)($_POST['timezone'] ?? $summary['timezone'] ?? $timezone);
            ?>
                <section class="setup-card"><div class="setup-card-top"><span class="setup-icon violet"><i class="fa-solid fa-file-circle-check" aria-hidden="true"></i></span><span class="setup-state <?= $supported ? 'done' : '' ?>"><?= $supported ? 'Analysis complete' : 'Import unavailable' ?></span></div><h2>Backup & Restore</h2><p><?= $escape($sourceTitle) ?> · <?= $escape($sourceFormatLabel) ?>. Review the configuration and any items needing attention.</p><div class="setup-counts"><?php foreach(['users'=>['Users','user_count'],'trunks'=>['SIP trunks','trunk_count'],'inbound_rules'=>['Incoming numbers','number_count'],'ring_groups'=>['Ring groups','ring_group_count']] as $key=>$item): ?><div><strong><?= (int)($importCounts[$key] ?? $summary[$item[1]] ?? 0) ?></strong><span><?= $item[0] ?></span></div><?php endforeach; ?></div>
                    <?php if(!empty($draft['warnings'])): ?><div class="setup-message warning"><strong>Check before switching</strong><ul><?php foreach($draft['warnings'] as $warning): ?><li><?= $escape($warning) ?></li><?php endforeach; ?></ul></div><?php endif; ?>
                    <?php if(!empty($draft['unsupported'])): ?><h3>Items requiring attention</h3><div class="setup-table-wrap"><table class="setup-table"><thead><tr><th>Feature</th><th>Items</th><th>Migration note</th></tr></thead><tbody><?php foreach($draft['unsupported'] as $item): ?><tr><td><?= $escape(ucwords(str_replace('_',' ',(string)($item['category'] ?? 'Configuration')))) ?></td><td><?= (int)($item['count'] ?? 0) ?></td><td><?= $escape($item['reason'] ?? 'Configure this feature after migration.') ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
                    <div class="setup-safety"><i class="fa-solid fa-shield-halved" aria-hidden="true"></i><span><?= $supported ? 'A fresh PBX service will be created. Connect your phones, check the provider settings, and test incoming and outgoing calls before going live.' : 'This analysis has not changed any PBX. Choose a supported configuration or provide a V20 sample for format validation.' ?></span></div>
                    <?php if($supported): ?><form method="post" class="setup-form"><?php $csrf(); ?><input type="hidden" name="action" value="create_import"><input type="hidden" name="draft_id" value="<?= $escape($draftId) ?>"><div class="setup-fields"><label>Company name<input name="company_name" required maxlength="120" value="<?= $escape($importCompany) ?>"></label><label>PBX name<input name="service_name" required maxlength="120" value="<?= $escape($importService) ?>"></label><?php $renderTenant((string)($_POST['tenant_uuid'] ?? $tenant)); $renderTimezone($importTimezone); ?></div><label class="setup-check-label"><input type="checkbox" name="acknowledge_limitations" value="1" required><span>I have reviewed the restore report. I will check phones and outside calls before going live.</span></label><div class="setup-actions"><a class="setup-button" href="?view=import">Choose another backup</a><button type="submit" class="setup-button primary">Restore backup<i class="fa-solid fa-arrow-right" aria-hidden="true"></i></button></div></form><?php else: ?><div class="setup-message error">This backup cannot be imported safely. Check the report, then upload a supported, unencrypted configuration.</div><a class="setup-button" href="?view=import">Choose another backup</a><?php endif; ?>
                </section>
            <?php elseif ($view === 'users'): ?>
                <section class="setup-card"><div class="setup-card-top"><span class="setup-icon"><i class="fa-solid fa-users" aria-hidden="true"></i></span><span class="setup-state"><?= (int)($counts['users'] ?? 0) ?> users</span></div><h2>Users</h2><p>Create extensions for your team, configure desk phones, and manage voicemail from here.</p><?php if(!empty($overview['users'])): ?><div class="setup-table-wrap"><table class="setup-table"><thead><tr><th>Extension</th><th>Name</th><th>Email</th></tr></thead><tbody><?php foreach($overview['users'] as $user): ?><tr><td><?= $escape($user['number'] ?? $user['extension'] ?? '') ?></td><td><?= $escape($user['name'] ?? $user['effective_caller_id_name'] ?? '') ?></td><td><?= $escape($user['email'] ?? $user['voicemail_mail_to'] ?? '') ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?><div class="setup-link-list"><?php $link('extension_view','/app/extensions/extensions.php','fa-user-plus','Users & extensions','Add people, update extensions, and view connection details.'); $link('device_view','/app/devices/devices.php','fa-phone','Desk phones','Provision and manage compatible phones.'); $link('voicemail_view','/app/voicemails/voicemails.php','fa-voicemail','Voicemail','Mailbox settings, greetings, and email delivery.'); ?></div></section>
            <?php elseif ($view === 'voice'): ?>
                <section class="setup-card"><div class="setup-card-top"><span class="setup-icon green"><i class="fa-solid fa-phone-volume" aria-hidden="true"></i></span><span class="setup-state"><?= (int)($counts['trunks'] ?? 0) ?> trunks · <?= (int)($counts['numbers'] ?? 0) ?> numbers</span></div><h2>Voice &amp; Chat</h2><p>SIP trunks connect your provider. Incoming numbers decide where calls arrive. Outbound rules decide how your team calls out.</p><?php if(!empty($overview['trunks'])): ?><div class="setup-table-wrap"><table class="setup-table"><thead><tr><th>Provider / trunk</th><th>Server</th><th>Status</th></tr></thead><tbody><?php foreach($overview['trunks'] as $item): ?><tr><td><?= $escape($item['name'] ?? $item['gateway'] ?? '') ?></td><td><?= $escape($item['host'] ?? $item['proxy'] ?? '') ?></td><td><?= filter_var($item['enabled'] ?? false,FILTER_VALIDATE_BOOLEAN) ? 'Enabled' : 'Disabled' ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?><div class="setup-link-list"><?php $link('gateway_view','/app/gateways/gateways.php','fa-tower-broadcast','SIP trunks','Provider servers, authentication, and registration settings.'); $link('destination_view','/app/destinations/destinations.php','fa-hashtag','Incoming numbers','Choose where each business number sends its calls.'); $link('outbound_route_view','/app/dialplans/dialplans.php?app_uuid=8c914ec3-9fc0-8ab5-4cda-6c9288bdc9a3','fa-arrow-up-right-from-square','Outbound calling rules','Route outgoing calls through your providers.'); ?></div></section>
            <?php elseif ($view === 'handling'): ?>
                <section class="setup-card"><div class="setup-card-top"><span class="setup-icon violet"><i class="fa-solid fa-diagram-project" aria-hidden="true"></i></span><span class="setup-state"><?= (int)($counts['ring_groups'] ?? 0) ?> ring groups</span></div><h2>Call Handling</h2><p>Ring a team, offer a menu, or change the destination after office hours.</p><?php if(!empty($overview['ring_groups'])): ?><div class="setup-table-wrap"><table class="setup-table"><thead><tr><th>Group</th><th>Extension</th></tr></thead><tbody><?php foreach($overview['ring_groups'] as $item): ?><tr><td><?= $escape($item['name'] ?? $item['ring_group_name'] ?? '') ?></td><td><?= $escape($item['number'] ?? $item['ring_group_extension'] ?? '') ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?><div class="setup-link-list"><?php $link('ring_group_view','/app/ring_groups/ring_groups.php','fa-people-group','Ring groups','Let several people answer your business calls.'); $link('ivr_menu_view','/app/ivr_menus/ivr_menus.php','fa-list','Digital receptionist','Give callers a menu for departments or extensions.'); $link('time_condition_view','/app/time_conditions/time_conditions.php','fa-business-time','Office hours','Set open hours, holidays, and after-hours destinations.'); $link('call_center_queue_view','/app/call_centers/call_center_queues.php','fa-headset','Call queues','Keep callers waiting for the next available agent.'); ?></div></section>
            <?php elseif ($view === 'settings'): ?>
                <section class="setup-card"><div class="setup-card-top"><span class="setup-icon"><i class="fa-solid fa-sliders" aria-hidden="true"></i></span></div><h2>System</h2><p>Manage company preferences and reusable setup templates. Administration stays within your permitted workspace.</p><div class="setup-link-list"><?php $link('pbx_service_view','/app/tenant_services/','fa-building','Company workspaces & PBX services','Open a service, invite tenants, or manage reusable setup templates.'); $link('smtp_settings_manage','/app/smtp_settings/','fa-envelope','Outgoing email','Configure delivery for voicemail and system messages.'); $link('domain_setting_view','/core/domain_settings/domain_settings.php','fa-gear','PBX preferences','Timezone, limits, and other company settings.'); $link('user_view','/core/users/users.php','fa-user-shield','Administrator accounts','Manage the people who administer this PBX.'); ?></div></section>
            <?php else: ?>
                <section class="setup-card setup-hero"><span class="setup-icon"><i class="fa-solid fa-wand-magic-sparkles" aria-hidden="true"></i></span><div><h2>Set Up a PBX</h2><p>Start with your company, add your people, and connect your phone provider. We'll build the PBX and its calling rules for you.</p><div class="setup-actions"><a class="setup-button primary" href="?view=wizard">Set up a new PBX<i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a><a class="setup-button" href="?view=import"><i class="fa-solid fa-file-import" aria-hidden="true"></i>Backup & Restore</a></div></div></section>
                <div class="setup-counts"><?php foreach(['users'=>'Users','trunks'=>'SIP trunks','numbers'=>'Incoming numbers','ring_groups'=>'Ring groups'] as $key=>$label): ?><div><strong><?= (int)($counts[$key] ?? 0) ?></strong><span><?= $label ?></span></div><?php endforeach; ?></div>
                <section class="setup-card"><h2>Your setup checklist</h2><p class="setup-subtitle">A clear next step at every stage.</p><ol class="setup-checklist"><?php foreach($overview['checklist'] ?? [] as $item): ?><li><span class="setup-checkmark <?= !empty($item['complete']) ? 'done' : '' ?>"><i class="fa-solid <?= !empty($item['complete']) ? 'fa-check' : 'fa-minus' ?>" aria-hidden="true"></i></span><div><h3><?= $escape($item['title'] ?? '') ?></h3><p><?= $escape($item['description'] ?? '') ?></p></div><?php if(!empty($item['url'])): ?><a class="setup-button" href="<?= $escape($item['url']) ?>"><?= !empty($item['complete']) ? 'Manage' : 'Set up' ?></a><?php endif; ?></li><?php endforeach; ?></ol></section>
                <div class="setup-grid"><section class="setup-card"><div class="setup-card-top"><span class="setup-icon green"><i class="fa-solid fa-users" aria-hidden="true"></i></span></div><h3>People first.</h3><p>Extensions, desk phones, and voicemail in one familiar section.</p><a class="setup-link" href="?view=users"><div><strong>Users</strong></div><i class="fa-solid fa-chevron-right" aria-hidden="true"></i></a></section><section class="setup-card"><div class="setup-card-top"><span class="setup-icon violet"><i class="fa-solid fa-diagram-project" aria-hidden="true"></i></span></div><h3>Make every call count.</h3><p>Groups, receptionist menus, queues, and office hours.</p><a class="setup-link" href="?view=handling"><div><strong>Call handling</strong></div><i class="fa-solid fa-chevron-right" aria-hidden="true"></i></a></section></div>
            <?php endif; ?>
        </div>
    </div>
</main>
<?php require_once PROJECT_ROOT.'/resources/footer.php'; ?>
